'use strict';
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const os = require('node:os');
const E = require('./evidence.js');
const url = file => pathToFileURL(path.resolve(__dirname,file)).href;
(async () => {
  const browser = await chromium.launch({ headless:true, ...(process.env.BROWSER_CHANNEL ? {channel:process.env.BROWSER_CHANNEL} : {}) });
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors=[],network=[];
    page.on('pageerror',e=>errors.push(e.message));
    page.on('request',r=>{if (/^https?:/.test(r.url())) network.push(r.url());});
    await page.goto(url('index.html'));
    assert(await page.locator('h1').isVisible());
    assert.equal(await page.locator('.source').count(),3);
    assert.equal(await page.locator('tbody tr').count(),5);
    assert(!(await page.locator('body').innerText()).includes(E.timing));
    await page.screenshot({path:path.join(os.tmpdir(),'exercise-03-desktop.png'),fullPage:true});
    await page.locator('#commit').click();
    assert.match(await page.locator('#commit-status').innerText(),/complete/);
    assert.equal(await page.evaluate(()=>document.activeElement.id),'commit-status');
    await page.locator('#review').click();
    assert((await page.locator('#gaps li').count())>10);
    await page.locator('#reset').click();
    assert(await page.locator('#results').isHidden());
    await page.locator('#decision').focus(); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Tab');
    assert.equal(await page.evaluate(()=>document.activeElement.id),'category');
    async function fill(action='timing') {
      for (const id of ['snapshot','association','sleep']) await page.locator(`[name="observation"][value="${id}"]`).check();
      for (const [id,value] of Object.entries({decision:'investigate',category:'synchronization',hypothesis1:'synchronization',hypothesis2:'product',action})) await page.locator('#'+id).selectOption(value);
      for (const [id,text] of Object.entries({rationale:'CI-01 records a snapshot.',support:'CODE-01 and HIST-01 suggest timing.',contradiction:'No direct contradiction supplied.',weakener:'A correlated error would weaken it.',actionReason:'Need evidence to distinguish timing from failure.',missing:'Correlated capture and cause of variation.'})) await page.locator('#'+id).fill(text);
    }
    await fill();
    await page.locator('#hypothesis2').selectOption('synchronization'); await page.locator('#commit').click();
    assert.match(await page.locator('#commit-status').innerText(),/distinct/);
    await page.locator('#hypothesis2').selectOption('product'); await page.locator('#commit').click();
    assert.equal(await page.locator('#timing-text').innerText(),E.timing);
    assert(await page.locator('#commit').isDisabled()); assert(await page.locator('#action').isDisabled());
    assert.equal(await page.locator('#actionReason').getAttribute('readonly'),'');
    await page.locator('#revision').fill('Timing contract helps, but the cause remains unresolved.');
    await page.locator('#review').click();
    assert.match(await page.locator('#gaps').innerText(),/All required/);
    await page.locator('#decision').selectOption('reject'); await page.locator('#rejection').selectOption('healthy');
    assert(await page.locator('#stale').isVisible()); await page.locator('#review').click();
    assert.match(await page.locator('#concerns').innerText(),/healthy/);
    await page.locator('#rejection').selectOption('certainty'); await page.locator('#review').click();
    assert.match(await page.locator('#concerns').innerText(),/No modeled/);
    await page.locator('#rationale').fill('<img src=x onerror=alert(1)>');
    assert.equal(await page.locator('#record img').count(),0);
    assert.match(await page.locator('#record').innerText(),/INITIAL DECISION[\s\S]*Claim decision: Investigate/);
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copied=text;}}}));
    await page.locator('#copy').click();
    assert.equal(await page.evaluate(()=>window.copied),await page.locator('#record').innerText());
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied');}}}));
    await page.locator('#copy').click();
    assert.equal(await page.evaluate(()=>window.getSelection().toString()),await page.locator('#record').innerText());
    await page.screenshot({path:path.join(os.tmpdir(),'exercise-03-reviewed.png'),fullPage:true});
    await page.locator('#reset').click();
    assert.equal(await page.locator('#timing-text').innerText(),'');
    assert(!(await page.locator('#record').innerText()).includes(E.timing));
    await fill('trace'); await page.locator('#priorTiming').check(); await page.locator('#commit').click();
    assert.match(await page.locator('#commit-status').innerText(),/pending/);
    assert(await page.locator('#reveal').isHidden());
    assert.match(await page.locator('#record').innerText(),/prior reading/);
    assert(!(await page.locator('#record').innerText()).includes(E.timing));
    await page.locator('#reset').click(); await fill('patch');
    for (const id of ['independent','failure']) await page.locator(`[value="${id}"][name="observation"]`).check();
    await page.locator('#hypothesis2').selectOption('policy'); await page.locator('#decision').selectOption('accept');
    await page.locator('#commit').click(); await page.locator('#review').click();
    assert.equal(await page.locator('#concerns li').count(),5);
    assert(await page.locator('#reveal').isHidden());
    await page.locator('#reset').click();
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(os.tmpdir(),'exercise-03-mobile.png'),fullPage:true});
    // A 720 CSS-pixel viewport checks reflow equivalent to 200% at 1440px; actual browser zoom remains a manual check.
    await page.setViewportSize({width:720,height:500});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.context().setOffline(true); await page.reload(); assert(await page.locator('#interactive').isVisible());
    const noJS = await browser.newContext({javaScriptEnabled:false,offline:true});
    const fallback = await noJS.newPage(); await fallback.goto(url('index.html'));
    await fallback.locator('noscript a').click(); assert.equal(await fallback.locator('.source').count(),3);
    assert(!(await fallback.locator('body').innerText()).includes(E.timing));
    await fallback.emulateMedia({media:'print'});
    await fallback.screenshot({path:path.join(os.tmpdir(),'exercise-03-worksheet-print.png'),fullPage:true});
    await fallback.emulateMedia({media:'screen'});
    await fallback.locator('a[href="requested-evidence.html"]').click();
    await fallback.locator('summary').click(); assert((await fallback.locator('body').innerText()).includes(E.timing));
    await fallback.locator('a[href="worked-example.html"]').click(); assert.match(await fallback.locator('h1').innerText(),/One defensible/);
    assert.deepEqual(errors,[]); assert.deepEqual(network,[]);
    console.log(`Passed browser ${browser.version()}: home/regression navigation, empty and sound attempts, request boundaries, snapshot/revision, wrong paths, keyboard sample, clipboard stubs, literal text, reset, responsive reflow, offline and no-JS fallback.`);
    console.log('Screenshots in '+os.tmpdir()+': exercise-03-{desktop,reviewed,mobile,worksheet-print}.png');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
