'use strict';
(()=>{const M=window.PathLab,$=id=>document.getElementById(id);let state=M.session(),active=0,pending='';
function node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function pathText(path){let s=M.initial();return path.map((id,i)=>{const o=M.options(i,s).find(o=>o.id===id);s=M.apply(s,i,id);return `${i+1}. ${M.stages[i]} — ${o.title}\n${o.text}`;}).join('\n\n');}
function report(result){return result.status+'\n'+result.profile.map(x=>x.join(': ')).join('\n')+'\n'+result.cases.map(c=>`${c.id}: ${c.observed}\n${c.verdict}`).join('\n')+'\n'+result.tradeoff+'\nWHY THIS ASSESSMENT\n'+result.rankingReason+'\nSTAGE EXPLANATIONS\n'+result.explanation.map(e=>[M.stages[e.stage]+' — '+e.title,'Selected: '+e.selected,'Why: '+e.why,'Benefit: '+e.benefit,'Limitation: '+e.limitation,'Downstream effect: '+e.effect,...e.corrections,'Later outcome: '+e.outcome,'When an alternative helps: '+e.alternative].join('\n')).join('\n\n')+'\n'+result.next;}
function record(){const first=state.first?'Path:\n'+pathText(state.first.path)+'\nJudgment: '+state.first.reason+'\n'+report(state.first.result):'Not evaluated yet.';$('record').textContent='FICTIONAL PATH SIMULATION — no tests executed\n\nFIRST EVALUATED ATTEMPT\n'+first+(state.firstComplete?'\n\nFIRST COMPLETED PATH\n'+pathText(state.firstComplete.path)+'\nJudgment: '+state.firstComplete.reason+'\n'+report(state.firstComplete.result):'')+'\n\nCURRENT PATH\n'+(pathText(state.path)||'No outputs selected.')+'\nJudgment: '+(state.reason||'Not recorded')+'\n'+(state.result?report(state.result):'Pending review; no current result.');}
function controls(){$('finish').disabled=state.path.length!==6||!$('reason').value.trim();$('stop').disabled=!$('reason').value.trim();$('finish-help').textContent=state.path.length<6?'Select outputs for all six stages and add a judgment to inspect a completed proposal. You may stop early with a reason.':!$('reason').value.trim()?'Add a short judgment to inspect consequences or stop for review.':'Ready to inspect. Your answers need not match the reference path.';}
function render(){const list=$('path');list.replaceChildren();let s=M.initial();for(let i=0;i<6;i++){const li=node('li');if(i<state.path.length){const o=M.options(i,s).find(o=>o.id===state.path[i]);const b=node('button',`${M.stages[i]}: ${o.title}`);b.type='button';b.className='path-button';b.addEventListener('click',()=>{active=i;pending='';renderStage();$('stage-title').focus();});li.append(b);s=M.apply(s,i,o.id);}else li.textContent=`${M.stages[i]} — awaiting input`;list.append(li);}$('path-status').textContent=`${state.path.length} of 6 outputs selected. ${state.first&&!state.result?'Revision pending; previous evaluated attempt preserved.':''}`;renderStage();controls();record();}
function renderStage(){$('stage-panel').hidden=active===6;if(active===6)return;const input=M.stateFor(state.path.slice(0,active));$('stage-counter').textContent=`STAGE ${active+1} / 6`;$('stage-title').textContent=M.stages[active];$('prompt').textContent=M.prompts[active];const context=$('input');context.replaceChildren();if(active){const pre=node('pre',pathText(state.path.slice(0,active)));context.append(pre);context.append(node('p','All selected outputs and their source references above are passed forward. Original requirements remain the authority.'));}else{context.append(node('p','The shared requirements and known gaps above. No risk conclusions have been supplied.'));}$('options').replaceChildren();for(const o of M.options(active,input)){const label=node('label');label.className='output-choice';const radio=node('input');radio.type='radio';radio.name='output';radio.value=o.id;radio.required=true;radio.checked=pending===o.id;radio.addEventListener('change',()=>{pending=o.id;$('next').disabled=false;$('choice-help').textContent='Selection ready. Passing it will update the path and regenerate later choices.';});const text=node('span');text.append(node('strong',o.title),node('span',o.text));label.append(radio,text);$('options').append(label);}$('next').disabled=!pending;$('next').textContent=active===5?'Pass output and review proposal':'Pass selected output to next stage';$('choice-help').textContent='Choose an output before continuing. It need not be correct.';}
$('next').addEventListener('click',()=>{if(!pending)return;M.select(state,active,pending);$('reason').value='';$('results').hidden=true;active=state.path.length;pending='';render();if(active<6)$('stage-title').focus();else $('reason').focus();});
$('reason').addEventListener('input',()=>{state.reason=$('reason').value;if(state.result){state.result=null;$('results').hidden=true;}controls();record();});
function evaluate(stop){if(!M.finish(state,$('reason').value,stop))return;const r=state.result;$('results').hidden=false;$('result-title').textContent=r.status;const panel=$('assessment');panel.replaceChildren();const profile=node('dl');r.profile.forEach(([a,b])=>profile.append(node('dt',a),node('dd',b)));panel.append(profile,node('p',r.tradeoff),node('h3','Why this assessment'),node('p',r.rankingReason));if(r.corrections.length){panel.append(node('h3','Corrections made along your path'));r.corrections.forEach(c=>panel.append(node('p',c)));}panel.append(node('h3','Why each choice matters'));for(const e of r.explanation){const detail=node('details');detail.className='stage-explanation';detail.append(node('summary',M.stages[e.stage]+' — '+e.title));const fields=[['Selected output',e.selected],['Why it is supported or flawed',e.why],['Benefit',e.benefit],['Limitation',e.limitation],['Downstream effect',e.effect],['Later outcome',e.outcome],['When an alternative helps',e.alternative]];const dl=node('dl');fields.forEach(([label,text])=>dl.append(node('dt',label),node('dd',text)));detail.append(dl);e.corrections.forEach(c=>detail.append(node('p',c)));panel.append(detail);}if(r.defects.length){panel.append(node('h3','Unresolved defects'));const ul=node('ul');r.defects.forEach(d=>ul.append(node('li',d)));panel.append(ul);}panel.append(node('h3','Prepared consequences'));r.cases.forEach(c=>{const box=node('section');box.className='outcome';box.append(node('h4',c.id),node('p',c.observed),node('strong',c.verdict));panel.append(box);});panel.append(node('p',r.next));const comparison=$('comparison');comparison.replaceChildren();if(state.first){comparison.append(node('h3','First attempt → current attempt'),node('p',`${state.first.result.status} → ${r.status}`));r.cases.forEach((c,i)=>comparison.append(node('p',`${c.id}: ${state.first.result.cases[i].verdict} → ${c.verdict}`)));}record();$('result-title').focus();}
$('finish').addEventListener('click',()=>evaluate(false));$('stop').addEventListener('click',()=>evaluate(true));
$('reset').addEventListener('click',()=>{state=M.session();active=0;pending='';$('reason').value='';$('results').hidden=true;$('assessment').replaceChildren();$('comparison').replaceChildren();$('copy-status').textContent='';render();$('stage-title').focus();});
$('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('record').textContent);$('copy-status').textContent='Record copied.';}catch{const range=document.createRange();range.selectNodeContents($('record'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);$('copy-status').textContent='Clipboard unavailable. Record selected; use your copy shortcut.';}});
$('interactive').hidden=false;render();})();
