(function(root){
'use strict';
const requirements={'REQ-01':'A registered user can request a password-reset link using their email address.','AC-01':'For a registered email, send a reset link.','AC-02':'The link expires 30 minutes after issue.','AC-03':'A successfully used link cannot be used again.','AC-04':'After a successful reset, the new password works and the old password does not.'};
const gaps='Password policy, exact behaviour at precisely 30 minutes, unregistered-email behaviour, rate limits, multiple outstanding links, session invalidation, and delivery-time guarantees are unspecified.';
const stages=['Extract requirements and gaps','Identify risks','Propose tests','Prioritize','Assess automation','Expert review'];
const prompts=['Extract supported behaviour with source IDs. Choose a scope for the credential-protection goal and keep gaps explicit.','Using the selected requirement summary and original sources, propose risks. Distinguish impact from unknown likelihood and challenge unsupported input.','Using the selected risks and linked requirements, propose at most three observable checks. State what each oracle proves.','Using the proposed checks, set a relative priority with an impact rationale. Keep unsupported or insufficient oracles visible.','Assess the selected proposal for repeatability, observable results, data/setup, and maintenance. All setup capabilities are unconfirmed.','Review the selected proposal against sources, credential protection, scope, and setup. Choose conditional implementation review, explicit return, or approval.'];
const order=[['focus','broad','policy'],['proxy','balanced','credentials'],['full','confirmation','extended'],['token','protection','easy'],['ready','defer','conditional'],['return','waive','review']];
const labels={credential:'AC-04: new password succeeds and old password is rejected in fresh unauthenticated sessions',confirmation:'AC-04 proxy: reset confirmation appears',replay:'AC-03: a successfully used token is rejected on reuse',expiry:'AC-02: an unused token at 31 minutes is rejected as expired',policy:'Unapproved policy: passwords shorter than 12 characters are rejected'};
const clone=x=>JSON.parse(JSON.stringify(x));
function initial(){return {scope:'',policy:false,risk:'',proxy:false,tests:[],priority:'',automation:'',review:'',notes:[]};}
function stateFor(path){let s=initial();path.forEach((id,i)=>{const option=options(i,s).find(o=>o.id===id);if(!option)throw Error('Invalid path at stage '+i);s=apply(s,i,id);});return s;}
function options(i,s){let list=[];const make=(id,title,text)=>({id,title,text});const inherited=s.policy?'The upstream 12-character rule has no approved source. ':'';const risk=s.risk==='balanced'?'credential, replay and expiry risks':'credential-protection risk';const testNames=s.tests.map(t=>labels[t]).join('; ');const issues=defects(s);const warning=issues.length?' Unresolved: '+issues.join(' '):'';
if(i===0)list=[make('focus','Credential-focused source summary','Preserve AC-04: new password works and old password does not. Keep AC-02/03 as linked token-control references; omit AC-01 request coverage from this small proposal. Password policy and exact expiry boundary remain open.'),make('broad','Full recovery behaviour summary','Retain REQ-01 and AC-01–04: request, expiry, single use, and both credential outcomes. Carry all source IDs forward for broader review; do not infer policy or exact-boundary rules.'),make('policy','Credential-strength interpretation','Preserve both AC-04 outcomes and AC-02/03 token controls. Interpret a successful reset as requiring a new password of at least 12 characters, so credential-strength checks accompany access checks. Exact expiry-boundary behaviour remains open.')];
if(i===1)list=[make('credentials','Credential-control emphasis',inherited+(s.policy?'Return that rule for clarification; remove it from this risk input. ':'')+'RISK-04: new credentials fail or old credentials still work. Prioritize access/control impact; likelihood unknown. '+(s.scope==='broad'?'Retain the broader source inventory but defer request/token-risk expansion.':'Keep token risks as references outside this focused risk output.')),make('balanced','Balanced recovery-risk emphasis',inherited+(s.policy?'Quarantine that unsupported rule as a question, not a product risk premise. ':'')+'RISK-04 plus RISK-03 token replay and RISK-02 expired-token use. All have access/control impact; likelihood unknown. Broader token coverage adds fixture and time-control work.'),make('proxy','Observable completion emphasis','Use a visible successful reset confirmation as evidence that credential protection works. Prioritize the risk that confirmation does not appear; likelihood unknown. '+(s.policy?'Carry the extracted 12-character policy into test design.':'Retain the selected source scope and defer direct credential probes.'))];
if(i===2){const correction=(s.proxy?'A confirmation cannot establish AC-04; replace that risk proxy with both credential outcomes. ':'')+(s.policy?'Reject the upstream length rule as unsupported and return it for clarification. ':'');list=[make('full','Focused credential check',correction+'For the '+risk+', check new-password success and old-password rejection in fresh sessions after reset. '+(s.risk==='balanced'?'Defer the identified replay/expiry checks from this sample.':'Retain token controls as omitted coverage.')+' One test idea; isolated accepted credentials required.'),make('extended','Credential and token checks',correction+'Check both AC-04 credential outcomes, reject token replay under AC-03, and reject an unused token at 31 minutes under AC-02. '+(s.risk==='balanced'?'Cover all three identified risks.':'Expand the narrow risk emphasis to include RISK-02/03 explicitly.')+' Three distinct ideas; add isolated token state and time-control setup.'),make('confirmation','Completion-based check','For the '+risk+', check that a successful reset confirmation appears; treat it as proof that the credential change works. '+(s.policy?'Also reject passwords below 12 characters as required upstream.':'Keep policy unresolved and omit direct authentication checks.')+' This uses the visible reset result as the primary oracle.')];}
if(i===3)list=[make('protection','Credential protection first','Prioritize '+(s.tests.includes('credential')?'both credential outcomes':'the selected credential proxy')+' for access/control impact; likelihood unknown. '+(s.tests.includes('replay')?'Token checks remain important but follow the credential check.':'Additional token coverage remains omitted.')+warning),make('token',s.tests.includes('replay')?'Equal access-control priority':'Focused priority with expansion deferred',s.tests.includes('replay')?'Give credentials, replay and expiry equal high relative priority; no likelihood ranking is evidenced. Broader execution setup is justified by their distinct access-control risks.'+warning:'Give the selected '+testNames+' high relative priority for access/control impact; explicitly defer token coverage until more setup capacity is known. No measured likelihood is supplied.'+warning),make('easy','Fastest checks first','Rank the selected '+testNames+' by ease of observing a result. Treat quick automation and a passing result as sufficient evidence of protection. This keeps the regression proposal inexpensive to review.')];
if(i===4){const setup='fresh sessions, isolated accepted credentials and cleanup'+(s.tests.includes('expiry')?', isolated used/unused tokens and controllable token age':'');list=[make('conditional','Conditional automation proposal','Propose repeatable regression automation for '+testNames+'. Confirm '+setup+' before implementation; maintain fixtures and assertions. '+(s.priority==='easy'?'Ease-based priority does not establish protection; flag it for review.':'Priority remains the selected workshop judgment.')+warning),make('defer','Defer execution pending setup','Keep '+testNames+' as design proposals. Request evidence that '+setup+' are feasible; use human-led fixture investigation first. No automation readiness claim yet.'+warning),make('ready','Ready-to-automate proposal','Recommend '+testNames+' for implementation using ordinary reset fixtures. Assume '+setup+' are already supported; the selected priority and observable outcomes are enough to approve automation readiness.')];}
if(i===5)list=[make('review',issues.length?'Return source defects for correction':'Conditional implementation review',issues.length?'Return the proposal to its earliest faulty stage: '+issues.join(' ')+' Do not approve the unresolved chain. Setup and coverage limits remain.':s.automation==='defer'?'Keep the source-backed proposal on hold for setup evidence; do not turn deferred execution into an approved implementation task.':'Send the supported sample for implementation review with setup conditions. '+(s.tests.length===1?'Focused credential coverage fits the brief; token and request coverage remain omitted.':'Three checks add token coverage and additional setup/maintenance effort.')+' Human-led clarity review remains separate; no tests have executed.'),make('return','Seek independent review first','Return the selected proposal for a peer to inspect source links, both credential outcomes, omitted coverage, and setup evidence. '+(issues.length?'Keep these defects unresolved: '+issues.join(' '):'No modeled source/oracle defect is identified, but independent review will delay implementation.')+' Do not report readiness.'),make('waive','Approve the completed chain','Approve the selected proposal because all six stages have outputs and the previous automation recommendation is recorded. Treat those completed handoffs as sufficient assurance; carry remaining questions into later implementation.')];
return (order[i]||[]).map(id=>list.find(o=>o.id===id));}
function apply(s,i,id){s=clone(s);if(i===0){s.scope=id==='broad'?'broad':'focus';s.policy=id==='policy';}if(i===1){s.risk=id==='balanced'?'balanced':'credentials';s.proxy=id==='proxy';if(id!=='proxy'&&s.policy){s.notes.push('Risks explicitly returned the unsupported length rule for clarification.');s.policy=false;}}if(i===2){s.tests=id==='extended'?['credential','replay','expiry']:id==='full'?['credential']:['confirmation'];if(id==='confirmation'&&s.policy)s.tests.push('policy');if(id!=='confirmation'){if(s.policy||s.proxy)s.notes.push('Test design corrected the inherited policy/proxy assumption against the original sources.');s.policy=false;s.proxy=false;}}if(i===3)s.priority=id;if(i===4)s.automation=id;if(i===5)s.review=id;return s;}
function defects(s){const d=[];if(s.policy)d.push('Password-length expectation is unsupported.');if(s.tests.includes('confirmation'))d.push('Confirmation alone misses AC-04 credential behaviour.');if(s.priority==='easy')d.push('Convenience is substituted for protection in prioritization.');if(s.automation==='ready')d.push('Unconfirmed setup is treated as available.');if(s.review==='waive')d.push('Completing all stages is not evidence that the proposal is sound.');return d;}
function explain(path){
const guidance={
focus:['AC-04 defines two credential outcomes; AC-02/03 remain references rather than invented rules.','Keeps review focused on the stated credential-protection goal.','Request and token coverage are deliberately omitted, not proven unnecessary.','Choose the broader summary when the task includes the whole recovery flow.'],
broad:['REQ-01 and AC-01–04 support the broader inventory; policy and boundary gaps remain unresolved.','Retains more source context for later coverage decisions.','More source context requires review; it does not itself add tests or establish coverage.','Choose a focused summary when only credential protection is in scope.'],
policy:['No supplied requirement establishes a minimum password length. The interpretation is unsupported.','It raises a potentially useful policy question, but cannot supply an oracle.','Passing it onward as a rule can create an unjustified failure claim.','Preserve the credential outcomes and ask the product owner to clarify password policy.'],
credentials:['RISK-04 derives from the two outcomes in AC-04; likelihood is explicitly unknown.','Prioritizes the access/control impact named in the brief.','Token risks remain outside this risk emphasis; this is not a complete risk analysis.','Use balanced risks when token misuse also merits coverage and setup effort.'],
balanced:['AC-02, AC-03 and AC-04 support expiry, replay and credential-control concerns.','Makes distinct token and credential risks available for test design.','Broader risk analysis can require more setup; it does not automatically mean those risks will be tested.','Use credential-only emphasis when the current task is deliberately narrow.'],
proxy:['A visible confirmation is an observation, not proof of both AC-04 outcomes.','A confirmation check can provide useful UI feedback evidence.','As a replacement for credential verification, it can hide an old-password-still-valid fault.','Retain confirmation only as supporting evidence; derive the risk from both credential outcomes.'],
full:['New-password success and old-password rejection directly match AC-04.','The selected oracle distinguishes the authored credential fault from the conforming example.','Replay and expiry are omitted; isolated accepted credentials and fresh sessions are still needed.','Use the extended set when distinct token coverage justifies the extra setup.'],
extended:['The three checks map to AC-04, AC-03 and AC-02; 31 minutes avoids the unspecified exact boundary.','Adds replay and expiry coverage while keeping both credential outcomes.','Requires token-state and time-control capabilities as well as credential setup; these are not confirmed.','Use the focused check when minimizing added setup is appropriate for the stated brief.'],
confirmation:['The selected confirmation oracle does not test the full meaning of AC-04.','It observes a visible reset outcome.','It passes E4-FAULT-01 despite the old password still working; ease of observation cannot compensate.','Select both credential assertions; include token checks only if their coverage and cost are justified.'],
protection:['The brief prioritizes credential protection; impact can justify that emphasis without measured likelihood.','Explains why credential behaviour should be checked first.','Priority does not strengthen a weak oracle or resolve an unsupported expectation.','Equal access-control priority is reasonable when distinct token checks are included and no finer ranking is evidenced.'],
token:['Source-backed access-control risks can receive equal priority; absent likelihood evidence should remain explicit.','Makes the coverage-versus-capacity decision visible.','A broader priority cannot create missing tests or repair their expected results.','Prefer explicit credential-first ordering when the current objective demands it.'],
easy:['Convenience and a passing result do not establish protection or coverage.','Implementation effort can inform planning as a secondary consideration.','Using ease as assurance can promote a cheap but ineffective check.','Prioritize source-backed impact first, then discuss effort as an explicit trade-off.'],
conditional:['The workshop states that setup capabilities are unconfirmed. Conditional design review preserves that boundary.','Connects repeatable regression value with concrete setup and maintenance requirements.','A conditional proposal is not executable or validated automation yet; earlier defects remain unresolved.','Defer when setup evidence is needed before even planning implementation.'],
defer:['Unknown setup justifies requesting evidence rather than claiming readiness.','Avoids assuming fixtures or time/session controls are available.','Adds human investigation and delays implementation; it does not repair source/oracle defects.','Conditional implementation review is possible for a supported proposal when dependencies are explicitly carried as conditions.'],
ready:['No evidence confirms the assumed setup capabilities.','It proposes an implementation direction, which may be useful for discussion.','Treating assumptions as available capabilities overstates readiness, even with a good oracle.','State conditions explicitly or defer for setup evidence.'],
review:['Expert review must assess sources, oracles and dependencies, not simply completion of stages.','Either returns unresolved issues or advances a supported proposal with conditions.','It does not validate the implementation or silently correct faulty earlier outputs.','Seek an independent review if additional assurance or setup evidence is needed.'],
return:['A reviewer can safely withhold approval while seeking source, oracle or setup evidence.','Avoids an unsupported readiness claim.','Stopping leaves the proposal unresolved and can delay a sound design; it does not repair defects.','Use conditional implementation review when the modeled issues are resolved and remaining setup conditions are explicit.'],
waive:['Completing six prompts is not evidence that their outputs are sound.','The recorded handoffs provide an audit trail, but not assurance.','Approval bypasses the substantive review gate, including any remaining defects or dependencies.','Inspect the proposal and either return it with reasons or advance it conditionally.']};
let s=initial();const final=stateFor(path);return path.map((id,i)=>{const before=clone(s),o=options(i,s).find(x=>x.id===id);s=apply(s,i,id);const [why,benefit,limitation,alternative]=guidance[id];let effect;
if(i===0)effect=s.policy?'The next prompt receives both AC-04 outcomes plus an unsupported 12-character rule.':s.scope==='broad'?'The next prompt receives the full recovery requirement inventory with explicit gaps.':'The next prompt receives a credential-focused summary and linked token-control references.';
if(i===1)effect=s.proxy?'The next prompt receives a confirmation-based proxy for protection.':'The next prompt receives '+(s.risk==='balanced'?'credential, replay and expiry risk proposals.':'a credential-control risk proposal.');
if(i===2)effect='The proposal now contains: '+s.tests.map(x=>labels[x]).join('; ')+'.';
if(i===3)effect=(id==='token'?(s.tests.includes('replay')?'All three selected access-control checks receive equal high priority.':'Only the selected check(s) receive priority; token expansion is deferred.'):id==='easy'?'Selected checks are ranked by convenience as if that established protection.':'Credential protection is emphasized before any selected token controls.')+' The test oracles are unchanged.';
if(i===4)effect='For '+s.tests.map(x=>labels[x]).join('; ')+', setup is '+(id==='ready'?'assumed available.':id==='defer'?'deferred for human investigation.':'explicitly conditional.')+(s.tests.includes('expiry')?' Token age and used/unused token state add dependencies.':' No replay/expiry test was added.');
if(i===5)effect=id==='return'?'The proposal stops for independent review; no repair or approval is implied.':id==='waive'?'The path attempts approval without substantive assurance.':defects(before).length?'The review returns these unresolved issues: '+defects(before).join(' '):before.automation==='defer'?'The proposal remains on hold for setup evidence.':'The supported sample advances only to conditional implementation review.';
const corrections=[];if(before.policy&&!s.policy)corrections.push('This choice explicitly removes the inherited length rule and returns password policy for clarification.');if(before.proxy&&!s.proxy)corrections.push('This choice replaces the inherited confirmation proxy with both credential outcomes.');
let outcome='No later change to this decision is implied.';if(id==='policy')outcome=path.length<2?'No later review yet; the unsupported rule remains in the selected input.':final.policy?'The unsupported rule remains unresolved in this path.':'A later selected output explicitly removed this rule; the earlier mistake remains in the record.';if(id==='proxy')outcome=path.length<3?'No test design yet; the proxy remains in the selected input.':final.proxy?'The proxy propagated into a confirmation-only test.':'A later test-design output explicitly replaced the proxy with full credential checks.';if(i===2)outcome=s.tests.includes('credential')?'The authored credential fault is detected by this oracle; it does not establish token-test execution.':'The authored credential fault is missed by this oracle.';
return {stage:i,id,title:o.title,selected:o.text,why,benefit,limitation,alternative,effect,corrections,outcome};});}
function evaluate(path,stopped=false){const s=stateFor(path),d=defects(s),complete=path.length===6;const held=stopped||s.review==='return'||(s.review==='review'&&(d.length>0||s.automation==='defer'));const ready=complete&&!held&&!d.length&&s.review==='review';const focused=s.tests.length===1&&s.tests[0]==='credential';const status=held?'Stopped for review — unresolved':!complete?'Incomplete path':d.length||s.review==='waive'?'Needs correction':ready&&focused?'Strongest fit for this brief':'Defensible with trade-offs';
const cases=[{id:'E4-CONFORM-01',observed:'Confirmation appears; new password authenticates; old password is rejected.',verdict:s.tests.length?'PASS for the selected credential/confirmation check':'No test proposed'},{id:'E4-FAULT-01',observed:'Confirmation appears; both passwords authenticate.',verdict:s.tests.includes('credential')?'FAIL — AC-04 fault detected':s.tests.includes('confirmation')?'PASS — credential fault missed':'Not covered'},{id:'E4-GAP-01',observed:'A seven-character fixture is accepted; no approved length policy is supplied.',verdict:s.tests.includes('policy')?'FAIL against an unsupported expectation':'Unresolved policy — no supported length verdict'}];
const explanation=explain(path);const rankingReason=held?'This path is held for review, so it is not ranked as ready. Stopping can contain risk but does not fix the proposal.':!complete?'Complete or explicitly stop the path before judging its overall usefulness.':!ready?'Unresolved defects or an unsound approval gate prevent readiness; convenience or extra coverage cannot compensate.':focused?'For the stated credential-protection brief, both AC-04 outcomes are checked without extra token-state/time-control setup. Conditional automation and substantive review preserve the limits. A broader supported path is useful when token coverage justifies that extra effort; equivalent focused paths may tie.':'This path checks AC-04 plus replay and expiry, adding supported coverage and token-state/time-control maintenance. It is defensible; the focused reference is preferred only for this narrow brief, not universally.';
return {status,ready,held,defects:d,state:s,cases,explanation,rankingReason,corrections:s.notes,profile:[['Source fidelity',s.policy?'Unsupported length rule remains.':'Source references and policy/boundary gaps preserved.'],['Credential protection',s.tests.includes('credential')?'Both credential outcomes checked.':s.tests.includes('confirmation')?'Confirmation cannot establish both credential outcomes.':'No credential test yet.'],['Coverage',s.tests.length?`${s.tests.length} distinct proposed idea(s). `+(s.tests.includes('expiry')?'Token controls included; AC-01 request coverage omitted.':'Token and AC-01 request coverage omitted.'):'No test ideas selected.'],['Practicality',s.automation==='ready'?'Setup availability assumed without evidence.':s.automation==='defer'?'Extra human investigation delays automation but makes uncertainty explicit.':s.automation==='conditional'?'Setup and maintenance conditions explicit; feasibility still unconfirmed.':'Not assessed yet.'],['Review discipline',held?'Stopped without claiming readiness.':s.review==='waive'?'Completion of stages is mistaken for assurance.':ready?'Conditional implementation review; no actual validation claimed.':'Review not completed.']],tradeoff:!s.tests.length?'No test proposal yet; coverage and effort trade-offs are unresolved.':focused?'Focused credential coverage minimizes added token setup; it omits useful token coverage.':s.tests.includes('replay')&&s.tests.includes('expiry')?'Broader token coverage adds protection checks and time/state-control maintenance. A supported broader path can be worthwhile.':'Confirmation is easy to observe, but it misses credential failure and adds no replay or expiry coverage.'+(s.tests.includes('policy')?' The extra length check relies on an unsupported policy.':''),next:d.length?'Return to the earliest source of the listed defect; reconsider dependent outputs.':held?'Resolve the review/setup request before claiming readiness.':'Validate setup and implementation; this is a prepared proposal, not a tested suite.'};}
const reference=['focus','credentials','full','protection','conditional','review'];
const alternative=['broad','balanced','extended','token','conditional','review'];
function session(){return {path:[],first:null,firstComplete:null,result:null,reason:'',stopped:false};}
function select(s,index,id){const input=stateFor(s.path.slice(0,index));if(index>s.path.length||!options(index,input).some(o=>o.id===id))throw Error('Invalid selection');s.path=[...s.path.slice(0,index),id];s.result=null;s.stopped=false;s.reason='';}
function finish(s,reason,stopped=false){if(!reason.trim()||(!stopped&&s.path.length!==6))return false;s.reason=reason;s.stopped=stopped;s.result=evaluate(s.path,stopped);if(!s.first)s.first=clone({path:s.path,reason,result:s.result});if(!stopped&&s.path.length===6&&!s.firstComplete)s.firstComplete=clone({path:s.path,reason,result:s.result});return true;}
const api={requirements,gaps,stages,prompts,labels,initial,stateFor,options,apply,defects,evaluate,reference,alternative,session,select,finish};if(typeof module!=='undefined')module.exports=api;else root.PathLab=api;
})(typeof globalThis!=='undefined'?globalThis:this);
