'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),M=require('./model');let completed=0,stops=0,revisions=0;const outcomes={};
function walk(p){const s=M.stateFor(p);if(p.length===6){completed++;const r=M.evaluate(p);outcomes[r.status]=(outcomes[r.status]||0)+1;assert(s.tests.length<=3);if(r.ready){assert(!s.policy);assert(s.tests.includes('credential'));assert.notEqual(s.priority,'easy');assert.equal(s.automation,'conditional');assert.equal(s.review,'review');}if(s.tests.includes('confirmation'))assert.match(r.cases[1].verdict,/missed/);if(s.tests.includes('credential'))assert.match(r.cases[1].verdict,/detected/);if(s.tests.includes('policy'))assert.match(r.cases[2].verdict,/unsupported/);for(let stage=0;stage<6;stage++){const session=M.session();session.path=[...p];assert(M.finish(session,'First judgment'));const first=JSON.stringify(session.first);const opts=M.options(stage,M.stateFor(p.slice(0,stage)));M.select(session,stage,opts.find(o=>o.id!==p[stage]).id);assert.equal(session.path.length,stage+1);assert.equal(session.result,null);assert.equal(session.reason,'');assert.equal(JSON.stringify(session.first),first);revisions++;}return;}
const opts=M.options(p.length,s);assert.equal(opts.length,3);assert.equal(new Set(opts.map(o=>o.id)).size,3);assert.equal(new Set(opts.map(o=>o.text)).size,3);assert(opts.every(o=>o.text&&!o.text.includes('undefined')));const stopped=M.evaluate(p,true);assert(stopped.held);assert(!stopped.ready);stops++;for(const o of opts)walk([...p,o.id]);}walk([]);assert.equal(completed,729);assert.equal(stops,364);
assert.equal(M.evaluate(M.reference).status,'Strongest fit for this brief');assert.equal(M.evaluate(['broad',...M.reference.slice(1)]).status,'Strongest fit for this brief');assert.equal(M.evaluate(M.alternative).status,'Defensible with trade-offs');
const inherited=M.stateFor(['policy','proxy']);assert(inherited.policy);assert(inherited.proxy);const corrected=M.stateFor(['policy','proxy','full']);assert(!corrected.policy);assert(!corrected.proxy);assert(corrected.notes.length);assert.notDeepEqual(M.options(2,M.stateFor(['focus','credentials'])),M.options(2,M.stateFor(['broad','balanced'])));assert.notDeepEqual(M.options(4,M.stateFor(M.reference.slice(0,4))),M.options(4,M.stateFor(M.alternative.slice(0,4))));
const short=M.session();assert(!M.finish(short,''));assert(!M.finish(short,'incomplete'));assert(M.finish(short,'Need a source',true));assert(!short.result.ready);short.path=[...M.reference];assert(M.finish(short,'Completed after review'));assert.equal(short.first.result.held,true);assert.deepEqual(short.firstComplete.path,M.reference);
const scenario=fs.readFileSync(path.resolve(__dirname,'../../../../tutorial-scenario.md'),'utf8');for(const [id,text]of Object.entries(M.requirements))assert(scenario.includes(`**${id}:** ${text}`));for(const c of M.evaluate(M.reference).cases)assert(scenario.includes(c.id));
cp.execFileSync(process.execPath,[path.join(__dirname,'build-pages.cjs'),'--check']);
for(const file of ['index.html','worksheet.html','fallback.html','worked-example.html']){const html=fs.readFileSync(path.join(__dirname,file),'utf8');for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const [target,anchor]=match[1].split('#');if(target){assert(!/^https?:|^\//.test(target));assert(fs.existsSync(path.resolve(__dirname,target)),target);}else if(anchor)assert(html.includes(`id="${anchor}"`),anchor);}if(['index.html','worksheet.html'].includes(file))assert(!html.includes('E4-FAULT-01'));if(file==='fallback.html'){assert(!html.includes('<script'));assert.equal((html.match(/class="route card"/g)||[]).length,1457);}}
console.log(JSON.stringify({completed,stops,revisions,outcomes}));console.log('Dependency variation, explicit inherited-fault corrections, tied defensible paths, non-compensable faults, snapshots, source parity, generated branching fallback and links passed.');
