// Run with Playwright available through Node resolution / NODE_PATH.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const os = require('node:os');
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}) });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    const errors = [], network = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (/^https?:/.test(request.url())) network.push(request.url()); });
    await page.goto(pathToFileURL(path.resolve(__dirname, 'index.html')).href);
    await page.locator('#interactive').waitFor({ state: 'visible' });
    await page.locator('header a.home-icon').click();
    assert.match(await page.locator('h1').innerText(), /From prompts to agentic testing workflows/);
    await page.locator('a[href="exercises/exercise-02-context-grounding/index.html"]').click();
    await page.locator('#interactive').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#sources .source').count(), 7);
    assert.match(await page.locator('#source-2').innerText(), /AC-02 · Release v0/);
    assert.match(await page.locator('#source-1').innerText(), /Release v1/);
    assert.match(await page.locator('#reason-source-1 option[value="OLD-01"]').innerText(), /AC-02 · Release v0/);
    assert.equal(await page.locator('#sources .source details[open]').count(), 0);
    assert.match(await page.locator('#sources .source').first().innerText(), /Product owner.*Current functional requirement/s);
    await page.locator('#sources .source details summary').first().click();
    assert.match(await page.locator('#sources .source details').first().innerText(), /registered user can request/);
    await page.locator('#decision-0').focus();
    await page.keyboard.press('ArrowDown');
    assert.equal(await page.locator('#decision-0').inputValue(), 'include');
    await page.keyboard.press('Tab');
    assert.equal(await page.evaluate(() => document.activeElement.tagName), 'SUMMARY');
    await page.locator('#review').click();
    assert(await page.locator('#results').isHidden());
    assert.match(await page.locator('#validation').innerText(), /Classify AC-01/);
    for (let i = 0; i < 7; i++) await page.locator(`#decision-${i}`).selectOption([0, 1].includes(i) ? 'include' : [3, 4].includes(i) ? 'defer' : 'exclude');
    await page.locator('#reason-source-1').selectOption('OLD-01');
    await page.locator('#reason-text-1').fill('Superseded by AC-02.');
    await page.locator('#reason-source-2').selectOption('CI-01');
    await page.locator('#reason-text-2').fill('Run observation for later diagnosis.');
    await page.locator('#conflict').fill('Current AC-02 says 30 minutes and supersedes OLD-01’s 15-minute rule.');
    await page.locator('#question-1').selectOption('unregistered');
    await page.locator('#question-2').selectOption('boundary');
    await page.locator('#review').click();
    assert(await page.locator('#results').isVisible());
    assert.match(await page.locator('#concerns').innerText(), /No modeled concern/);
    await page.locator('#question-2').selectOption('duration');
    assert(await page.locator('#stale').isVisible());
    await page.locator('#review').click();
    assert.match(await page.locator('#concerns').innerText(), /already answered/);
    await page.locator('#question-2').selectOption('custom');
    assert(await page.locator('#custom-field-2').isVisible());
    await page.locator('#custom-2').fill('What happens with multiple outstanding links?');
    await page.locator('#review').click();
    assert.match(await page.locator('#package').textContent(), /multiple outstanding links/);
    await page.locator('#decision-2').selectOption('include');
    await page.locator('#history').check();
    await page.locator('#review').click();
    assert.match(await page.locator('#validation').innerText(), /Complete reason 1/);
    await page.locator('#reason-source-1').selectOption('NOISE-01');
    await page.locator('#review').click();
    assert.match(await page.locator('#strengths').innerText(), /superseded history/);
    await page.locator('#history').uncheck(); await page.locator('#review').click();
    assert.match(await page.locator('#concerns').innerText(), /15-minute/);
    await page.locator('#results details').first().locator('summary').click();
    assert.match(await page.locator('#rationale').innerText(), /SUGGEST-01/);
    await page.locator('#results details').last().locator('summary').click();
    await page.locator('#conflict').fill('<img src=x onerror=alert(1)>');
    await page.locator('#review').click();
    assert.equal(await page.locator('#package img').count(), 0);
    assert.match(await page.locator('#package').textContent(), /<img/);
    await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async text => { window.copied = text; } } }));
    await page.locator('#copy').click();
    assert.equal(await page.evaluate(() => window.copied), await page.locator('#package').textContent());
    await page.locator('#reset').click();
    assert(await page.locator('#results').isHidden());
    assert.equal(await page.locator('#progress').innerText(), '0 of 7 sources classified.');
    await page.screenshot({ path: path.join(os.tmpdir(), 'exercise-02-new-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(os.tmpdir(), 'exercise-02-new-mobile.png'), fullPage: true });
    await page.context().setOffline(true); await page.reload();
    assert(await page.locator('#interactive').isVisible());
    await page.locator('a[href="worksheet.html"]').first().click();
    assert.equal(await page.locator('.source-grid .source').count(), 7);
    assert.equal(await page.locator('h2').filter({ hasText: 'Source reference: full text' }).count(), 1);
    await page.locator('a[href="worked-example.html"]').click();
    assert.match(await page.locator('h1').innerText(), /One defensible package/);
    const noJS = await browser.newContext({ javaScriptEnabled: false });
    const fallback = await noJS.newPage();
    await fallback.goto(pathToFileURL(path.join(__dirname, 'index.html')).href);
    assert(await fallback.locator('noscript').isVisible());
    await fallback.locator('noscript a').first().click();
    assert.equal(await fallback.locator('.source-grid .source').count(), 7);
    assert.deepEqual(errors, []); assert.deepEqual(network, []);
    console.log('Passed browser flow: home navigation, compact cards, keyboard selection, validation, alternative paths, feedback, revision, literal free text, copy, reset, 390px layout, offline and no-JS fallback.');
    console.log(`Screenshots: ${path.join(os.tmpdir(), 'exercise-02-new-desktop.png')} and ${path.join(os.tmpdir(), 'exercise-02-new-mobile.png')}`);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
