'use strict';
(()=>{
const M=window.LoopBuilder,S=window.LoopSources,$=id=>document.getElementById(id);
let order=[],bank=M.shuffle(M.blocks.map(b=>b.id)),attempts=[],latest=null,dragId=null,token=0;
const config=()=>Object.fromEntries(Object.keys(M.defaults).map(k=>[k,$(k).value]));
const elem=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function source(id){const d=elem('details','source');d.append(elem('summary','',id),elem('pre','',S[id]));return d;}
for(const id of ['BATCH-01','ACs','CI-01','CODE-01','TIM-01','DATA-01','BATCH-APPROVAL'])$('source-pack').append(source(id));
function changed(){token++;$('run').disabled=$('suite').disabled=false;if(latest){$('stale').hidden=false;$('run-status').textContent='Revision in progress. Previous attempt is preserved.';}document.querySelectorAll('.block').forEach(n=>n.classList.remove('active','passed','collapsed','unreached'));}
function button(label,action,id,title){const b=elem('button','',label);b.type='button';b.dataset.action=action;b.dataset.id=id;b.setAttribute('aria-label',title);return b;}
function card(id,inCanvas){const b=M.byId[id],n=elem('article','block');n.dataset.id=id;n.draggable=true;n.setAttribute('aria-label',b.name);const tag=elem('div','block-tag');tag.append(elem('span','grip','⠿'),document.createTextNode(b.tag));n.append(tag,elem('h3','',b.name),elem('p','',b.text));const controls=elem('div','block-controls');if(inCanvas){const i=order.indexOf(id);n.append(elem('span','step-number',String(i+1).padStart(2,'0')));const up=button('↑','up',id,'Move '+b.name+' up'),down=button('↓','down',id,'Move '+b.name+' down');up.disabled=i===0;down.disabled=i===order.length-1;controls.append(up,down,button('Return','remove',id,'Return '+b.name+' to library'));}else controls.append(button('Add →','add',id,'Add '+b.name+' to canvas'));n.append(controls);return n;}
function render(){const old=$('loopTo').value;$('bank').replaceChildren(...bank.map(id=>card(id,false)));$('canvas').replaceChildren();for(let i=0;i<=order.length;i++){const gap=elem('div','drop-zone'+(!order.length?' empty':''),!order.length?'Drop your first block here. Build a workflow, not just a list.':'');gap.dataset.index=i;gap.setAttribute('aria-label','Insert block at position '+(i+1));$('canvas').append(gap);if(i<order.length)$('canvas').append(card(order[i],true));}$('bank-count').textContent='· '+bank.length;$('canvas-count').textContent=order.length+' blocks';$('loopTo').replaceChildren(new Option('Connect to a canvas block…',''),...order.map(id=>new Option(M.byId[id].name,id)));if(order.includes(old))$('loopTo').value=old;}
function place(id,index){if(!M.byId[id])return;const old=order.indexOf(id);if(old>=0){order.splice(old,1);if(old<index)index--;}bank=bank.filter(x=>x!==id);order.splice(Math.max(0,Math.min(index,order.length)),0,id);changed();render();$('move-status').textContent=M.byId[id].name+' placed at position '+(order.indexOf(id)+1)+'.';}
function remove(id){if(!order.includes(id))return;order=order.filter(x=>x!==id);bank.push(id);changed();render();$('move-status').textContent=M.byId[id].name+' returned to library.';}
function drawLoop(){const target=$('loopTo').value,from=$('canvas').querySelector('[data-id=decide]'),to=$('canvas').querySelector(`[data-id="${target}"]`);$('canvas').querySelector('svg')?.remove();$('loop-link').hidden=!target;$('loop-link').textContent=target?'↶ CONTINUE → '+M.byId[target].name+' · preserve workflow state and remaining execution allowance':'';if(!from||!to)return;const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),line=document.createElementNS(ns,'path');svg.classList.add('loop-wire');svg.setAttribute('aria-hidden','true');const rect=$('canvas').getBoundingClientRect(),a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x=rect.width-6,y1=a.top-rect.top+a.height/2,y2=b.top-rect.top+18;svg.setAttribute('viewBox',`0 0 ${rect.width} ${rect.height}`);line.setAttribute('d',`M ${x-18} ${y1} H ${x} V ${y2} H ${x-18} l 6 -5 m -6 5 l 6 5`);svg.append(line);$('canvas').append(svg);}
const observer=new MutationObserver(records=>{if(records.some(r=>[...r.addedNodes,...r.removedNodes].some(n=>n.nodeType===1&&n.matches('.block,.drop-zone'))))requestAnimationFrame(drawLoop);});observer.observe($('canvas'),{childList:true});
document.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const {action,id}=b.dataset;if(action==='add')place(id,order.length);if(action==='up')place(id,order.indexOf(id)-1);if(action==='down')place(id,order.indexOf(id)+2);if(action==='remove')remove(id);const next=document.querySelector(`article[data-id="${id}"] button:not(:disabled)`);next?.focus();});
document.addEventListener('dragstart',e=>{const card=e.target.closest('.block');if(!card)return;dragId=card.dataset.id;e.dataTransfer.setData('text/plain',dragId);e.dataTransfer.effectAllowed='move';card.classList.add('dragging');});
document.addEventListener('dragend',()=>{dragId=null;document.querySelectorAll('.dragging,.drag-over').forEach(n=>n.classList.remove('dragging','drag-over'));});
document.addEventListener('dragover',e=>{const target=e.target.closest('.drop-zone,#bank');if(!target||!dragId)return;e.preventDefault();e.dataTransfer.dropEffect='move';target.classList.add('drag-over');});
document.addEventListener('dragleave',e=>e.target.closest('.drop-zone,#bank')?.classList.remove('drag-over'));
document.addEventListener('drop',e=>{const target=e.target.closest('.drop-zone,#bank');if(!target)return;e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(!M.byId[id])return;if(target.id==='bank')remove(id);else place(id,Number(target.dataset.index));dragId=null;document.querySelectorAll('.drag-over,.dragging').forEach(n=>n.classList.remove('drag-over','dragging'));});
$('shuffle').addEventListener('click',()=>{bank=M.shuffle(bank);render();$('move-status').textContent='Unused blocks shuffled. Your workflow and recorded attempts are unchanged.';});
for(const key of Object.keys(M.defaults))$(key).addEventListener('change',changed);
$('loopTo').addEventListener('change',drawLoop);window.addEventListener('resize',drawLoop);
function display(result){document.querySelectorAll('.block').forEach(n=>n.classList.remove('active','passed','collapsed','unreached'));const box=elem('article','result-card'+(result.ok?'':' fail'));if(result.ok)box.append(elem('p','eyebrow','CONTROLLED OUTCOME'));box.append(elem('h3','',result.outcome),elem('p','',result.reason),elem('p','meta',`${result.count} tool execution attempt(s) · Retained evidence: ${result.evidence.join(', ')||'none'}. Fictional simulation; no actual fix verified.`));if(result.ok&&(!$('reviewer').value.trim()||!$('rationale').value.trim()))box.append(elem('p','meta','Before submitting this design for human review, record your reviewer and reasoning in the configuration section. A passing simulation does not assess them.'));if(result.runs){const report=elem('section','triage-report');report.append(elem('h4','','Per-run triage report'));for(const row of result.runs){const item=elem('article','source');item.dataset.run=row.run;item.append(elem('h4','','Run '+row.run+' · '+row.status),elem('p','',row.group),elem('p','','Evidence: '+(row.evidence.join(', ')||'none checked')),elem('p','','Uncertainty: '+row.uncertainty),elem('p','','Next owner/action: '+row.nextOwner));report.append(item);}box.append(report);}$('result').replaceChildren(box);$('trace').replaceChildren(...result.events.map(e=>elem('li','',`${M.byId[e.id]?.name||'Workflow'} — ${e.text}`)));$('trace-panel').hidden=false;const revealed=new Set();result.events.filter(e=>e.id==='act').forEach(e=>{for(const id of Object.keys(S))if(e.text.includes(id))revealed.add(id);});$('reveals').replaceChildren(...[...revealed].map(source));if(!$('stale').hidden)return;if(!result.ok){const bad=order.indexOf(result.id);document.querySelector(`#canvas [data-id="${result.id}"]`)?.classList.add('collapsed');if(bad>=0)order.slice(bad+1).forEach(id=>document.querySelector(`#canvas [data-id="${id}"]`)?.classList.add('unreached'));}else document.querySelectorAll('#canvas .block').forEach(n=>n.classList.add('passed'));}
function saveAttempt(scenario,result){const a={number:attempts.length+1,order:[...order],configuration:config(),scenario,reviewer:$('reviewer').value,rationale:$('rationale').value,result};attempts.push(a);latest=a;return a;}
async function animate(result){const own=++token;$('run').disabled=$('suite').disabled=true;$('run-status').textContent='Following your workflow steps…';const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;for(const event of result.events){if(own!==token)return;document.querySelectorAll('.block.active').forEach(n=>n.classList.remove('active'));document.querySelector(`#canvas [data-id="${event.id}"]`)?.classList.add('active');if(!reduced)await new Promise(r=>setTimeout(r,70));}if(own!==token)return;display(result);$('run').disabled=$('suite').disabled=false;$('run-status').textContent='Attempt '+attempts.length+' recorded. '+(result.ok?'Inspect the decision trace and test a different observation.':'Revise the highlighted step or rule, then run again.');}
$('run').addEventListener('click',()=>{const scenario=$('scenario').value,result=M.run(order,config(),scenario);changed();$('stale').hidden=true;$('suite-results').replaceChildren();saveAttempt(scenario,result);animate(result);});
$('suite').addEventListener('click',()=>{changed();$('stale').hidden=true;$('suite-results').replaceChildren();const results=M.scenarios.map(([id,label])=>{const result=M.run(order,config(),id),a=saveAttempt(id,result),b=elem('button','',label);b.type='button';b.append(elem('small','',result.outcome));b.addEventListener('click',()=>{display(a.result);$('run-status').textContent='Showing recorded attempt '+a.number+' · '+label;});$('suite-results').append(b);return result;});display(results.find(r=>!r.ok)||results[0]);$('run-status').textContent=results.every(r=>r.ok)?'All four situations end within the modeled controls. Review the different endings and your written rationale.':'At least one situation exposed a broken workflow. Open each result to compare the consequences.';});
$('scenario').addEventListener('change',()=>{if(latest)$('run-status').textContent='Evidence situation changed. Run to test it; displayed feedback still describes the recorded attempt.';});
function record(){return JSON.stringify({exercise:'6 Loop Workshop',notice:'Fictional deterministic simulation; written rationale needs human review.',currentDesign:{order,configuration:config(),reviewer:$('reviewer').value,rationale:$('rationale').value},attempts,revisionAndHandoff:$('reflection').value},null,2);}
$('copy').addEventListener('click',async()=>{const text=record();try{await navigator.clipboard.writeText(text);$('copy-status').textContent='Design, all attempts, and reflection copied.';}catch{$('export').hidden=false;$('export').value=text;$('export').focus();$('export').select();$('copy-status').textContent='Clipboard unavailable. The complete record is selected below; use your device copy command.';}});
$('reset').addEventListener('click',()=>{token++;order=[];bank=M.shuffle(M.blocks.map(b=>b.id));attempts=[];latest=null;for(const [k,v]of Object.entries(M.defaults))$(k).value=v;for(const k of ['reviewer','rationale','reflection','export'])$(k).value='';for(const id of ['result','trace','reveals','suite-results','run-status','copy-status'])$(id).replaceChildren();$('stale').hidden=$('trace-panel').hidden=$('export').hidden=true;$('run').disabled=$('suite').disabled=false;render();$('move-status').textContent='New shuffled workshop. Previous attempts cleared.';$('shuffle').focus();});
$('interactive').hidden=false;render();
})();
