/* Fictional teaching evidence. Original Exercise 6 cards retained; batch cards extend 6-B. */
(function(r){const s={
  "ACs": "- **REQ-01:** A registered user can request a password-reset link using their email address.\n- **AC-01:** For a registered email, send a reset link.\n- **AC-02:** The link expires 30 minutes after issue.\n- **AC-03:** A successfully used link cannot be used again.\n- **AC-04:** After a successful reset, the new password works and the old password does not.\n\nIntentional gaps remain: unregistered-email behaviour; password composition/length rules; rate limits; exact behaviour at precisely 30 minutes; multiple outstanding links; session invalidation; delivery-time guarantees. Record questions rather than invent expected results. Use times clearly before/after expiry for supported examples and keep exact-boundary assertions pending clarification.",
  "TIM-01": "For a valid, unused, unexpired token and an accepted password fixture in the isolated integration environment, reset submission must complete successfully and show a success confirmation within 3,000 ms of submission. The confirmation is created only after a successful reset response. A response/confirmation earlier or later than one second can satisfy this contract. A response error or confirmation after 3,000 ms requires investigation; it must not be normalized away by extending the timeout. This contract does not assert whole-service health, production performance, or email delivery time.",
  "DATA-01": "Each run creates a distinct registered account, old/new accepted-password fixtures, and a fresh unused token. Submission occurs 60 seconds after token issue. No other test uses this account or token. The negative-policy probe uses a separate fresh fixture. Authentication checks use fresh unauthenticated sessions; cleanup follows each run. Fixture acceptance is test setup evidence, not a general password-policy specification.",
  "CODE-01": "`existsNow` is an immediate snapshot with no implicit wait. The harness retains diagnostic capture for three seconds after submission even if an assertion fails. The policy probe is a separate test, not a later line executed after the failed assertion.\n\n```text\n01 test reset_completion:\n02   account, token, acceptedNewPassword = isolatedResetFixture()\n03   openResetForm(token)\n04   submitNewPassword(acceptedNewPassword)  // asynchronous request\n05   sleep(1000 milliseconds)\n06   assert existsNow(\"reset-confirmation\")\n07   cleanup(account)\n\n08 test proposed_password_policy:\n09   account, token = separateResetFixture()\n10   submitNewPassword(\"short-example\", token)\n11   assert result == rejected_because_length_below_12\n12   cleanup(account)\n```\n\nLine 5 is a synchronization risk relative to TIM-01. Line 6 does not establish AC-04. Line 11 invents a policy. Only evidence about the failing run can determine which issue explains that observed failure. Cleanup in a real implementation must run even when assertions fail; the pseudocode omits language-specific teardown syntax and participants may note this additional review finding.",
  "CI-01": "```text\nrun=204 application=app-a42 tests=test-t17 test=reset_completion\nenvironment=isolated-integration fixture=account-204 request=reset-204\nrelative time origin: reset submission (same runner monotonic clock)\nt+0000ms submit reset-204\nt+1000ms fixed delay completes\nt+1002ms existsNow(reset-confirmation) -> false\nt+1003ms assertion failed; diagnostics continue until t+3000ms\n```\n\nThis proves that the element was absent at the snapshot. It does not establish a timeout breach, failed reset, or unstable service. The password-policy test is not the failed test here.",
  "HIST-01": "| Run | Response completed | Confirmation created | Snapshot | Test outcome |\n| --- | --- | --- | --- | --- |\n| 201 | 620 ms | 660 ms | 1002 ms | Pass |\n| 202 | 1320 ms | 1360 ms | 1002 ms | Fail |\n| 203 | 810 ms | 850 ms | 1002 ms | Pass |\n| 204 | 1420 ms | 1460 ms | 1002 ms | Fail |\n| 205 | 730 ms | 770 ms | 1002 ms | Pass |\n\nAll rows use app-a42/test-t17, isolated fixtures, and the same configured environment. Apparently equivalent runs vary in observed timing. The five-run sample motivates a flaky-test hypothesis; it is not a production reliability estimate. The report derives its timestamps from captured run events, so it is not independent corroboration of those events. It also does not prove why latency varied.",
  "TRACE-01": "```text\nrun=204 request=reset-204 fixture=account-204\nt+0000ms reset submitted\nt+1002ms DOM snapshot: no reset-confirmation element\nt+1420ms reset-204 response: 200, reset outcome success\nt+1460ms UI creates reset-confirmation with success text\nt+3000ms diagnostic capture ends\n```\n\nTimes share the CI monotonic origin. This supports a timing race between the snapshot and confirmation; TIM-01 is needed to judge the timing expectation. It does not independently establish successful authentication with the new password or rejection of the old password.",
  "CHANGE-01": "Application app-a42, test-t17, and environment configuration env-e8 were unchanged across runs 201–205. No test-file diff exists between those runs. Runtime resource utilization was not captured. Unchanged versions narrow a recent-change hypothesis but do not exclude environmental variation, nondeterminism, or a pre-existing product defect.",
  "VALID-01": "This card represents a simulated execution, never a real CI call. Ask the participant to record approval before revealing it.\n\nWith isolated fixtures and controlled confirmation delays of 700 ms and 1,460 ms, the original snapshot test passes the first and fails the second. A proposed test that waits for a successful confirmation with a maximum of 3,000 ms passes both. It fails at 3,000 ms when confirmation is withheld. Separate fresh-session checks establish new-password success and old-password rejection in both successful comparison cases. A deliberately injected old-password-still-valid fault is detected by the stronger assertions, while the original confirmation-only assertion passes it.\n\nThese authored examples illustrate discriminating validation, not a verified patch. Recommend implementing and validating the change against the actual system before accepting it. Do not claim all intermittent failures are fixed.",
  "GAP-01": "TRACE-01 cannot be retrieved; the correlated capture was not retained. Record the gap and request a fresh approved diagnostic run or escalate to the test owner. Do not synthesize a missing trace from the historical aggregate. Finishing with “cause unresolved” is valid.",
  "CONFLICT-01": "The returned trace is labeled run=207/request=reset-207, while the failure is run=204/request=reset-204. Reject correlation; request the correct capture. If it cannot be obtained within permitted actions, escalate. Do not overwrite CI-01 or silently treat the mismatched trace as confirmation.",
  "ERROR-01": "Workshop tool-error variant: retrieval failed before a capture was returned. One dispatched attempt was consumed. Preserve the error and gap; no run evidence was obtained.",
  "REQUEST-01": "Workshop request receipt: the test owner has received the run=204/request=reset-204 diagnostic request. No new capture is available in this exercise. Escalate the unresolved question; this receipt is not diagnostic evidence.",
  "BATCH-01": "Fictional triage queue: three distinct failures in isolated integration. Each run uses DATA-01 fixtures; none shares an account or token. These are starting observations, not diagnoses.\n204 / reset-204 / account-204: reset_completion; confirmation absent at 1,002 ms (CI-01). Capture available on request.\n208 / reset-208 / account-208: credential_invalidation; CI reports that an old-password sign-in was accepted after a successful reset. Authentication/session capture available on request. Check fixture and session identity before concluding an AC-04 defect.\n209 / reset-209 / account-209: reset_completion; CI reports no confirmation by the TIM-01 deadline. Extended diagnostic capture available on request. Do not group it with 204 solely because both tests mention confirmation.\nAll use app-a42 and env-e8. Run 204 uses test-t17; 208 uses credential checks and 209 uses a bounded confirmation check. Do not assume the tests have identical implementations.\nTask: triage all three, propose provisional groups, choose follow-up actions, and deliver a per-run evidence/uncertainty/next-owner report within 1–5 total tool execution attempts. Uninvestigated runs must stay visible. No production writes.",
  "TRACE-208": "Fictional tool result. run=208 request=reset-208 fixture=account-208, isolated integration. Fresh unused token, accepted old/new fixtures, reset at token age 60 seconds. Successful reset response at 800 ms; confirmation at 840 ms. After completion, separate fresh unauthenticated sessions accept both the new AND the old password for account-208. Account and request identities match the CI failure. This observation contradicts AC-04 in this run and warrants product/security-owner investigation. It does not identify root cause, prove production exposure, or justify treating 204 as the same defect.",
  "TRACE-209": "Fictional tool result. run=209 request=reset-209 fixture=account-209. DATA-01 preconditions verified. All times use submission as monotonic origin. At 3,000 ms no success confirmation; response succeeds at 3,160 ms and confirmation appears at 3,200 ms. This run uses extended diagnostics to 4,000 ms (not run 204's three-second capture). This breaches TIM-01 in isolated integration. No credential checks or resource-utilization data captured. Investigate with the service owner; do not fix by increasing the accepted deadline or infer the latency cause.",
  "BATCH-APPROVAL": "Fictional permission rule: read access is permitted for each listed run's diagnostic capture. In the normal, missing and mismatch situations, the test owner approves only the isolated run-204 synchronization/assertion comparison using DATA-01 fixtures. This does not authorize comparisons or changes for 208/209, production access, or release. In the denied situation that comparison approval is absent. Check before execution; blocked proposals consume no execution attempt."
};if(typeof module==="object"&&module.exports)module.exports=s;else r.LoopSources=s;})(globalThis);
