'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),M=require('./model.js');
const order=M.blocks.filter(b=>!b.optional&&!b.bad).map(b=>b.id),config={limit:'4',policy:'adaptive',evidence:'identity',threshold:'comparison',loopTo:'assess',invalid:'escalate',authority:'scoped'};
assert(M.structure(order).ok);const perm=(xs)=>xs.length?xs.flatMap((v,i)=>perm(xs.filter((_,j)=>j!==i)).map(p=>[v,...p])):[[]];for(const p of perm(order.slice(0,3)))assert(M.structure([...p,...order.slice(3)]).ok);
for(const id of order){const r=M.run(order.filter(x=>x!==id),config);assert(!r.ok,id);assert(r.reason.length>40);}
for(const id of ['trust','retry','release']){const ids=[...order];ids.splice(id==='release'?10:7,0,id);const r=M.run(ids,config);assert(!r.ok);assert.equal(r.id,id);}
const swapped=[...order];[swapped[5],swapped[6]]=[swapped[6],swapped[5]];assert.equal(M.run(swapped,config).id,'act');assert.match(M.run(swapped,config).reason,/Check permissions/);
const optional=[...order];optional.splice(9,0,'versions');assert(M.run(optional,config).ok);assert.match(M.run(optional,config).events.find(e=>e.id==='versions'&&e.text.includes('unresolved')).text,/not been retrieved/);
let cases=0,good=0;
for(const policy of ['adaptive','coverage','fixed','green'])for(const evidence of ['identity','trust'])for(const threshold of ['bounded','comparison','green'])for(const invalid of ['escalate','request','accept'])for(const authority of ['scoped','assume'])for(const loopTo of order)for(const limit of ['1','2','3','4','5'])for(const [scenario]of M.scenarios){const c={policy,evidence,threshold,invalid,authority,loopTo,limit},r=M.run(order,c,scenario);assert(r.count<=Number(limit));assert(r.count<=5);assert(r.reason.length>40);if(r.ok){good++;assert(['adaptive','coverage'].includes(policy));assert.equal(evidence,'identity');assert.equal(authority,'scoped');assert.equal(loopTo,'assess');if(r.outcome==='Recommendation ready'){assert(r.evidence.includes('TRACE-01'));if(threshold==='comparison')assert(r.evidence.includes('VALID-01'));assert.notEqual(threshold,'green');}if(scenario==='denied'&&threshold==='comparison')assert(!r.evidence.includes('VALID-01'));}cases++;}
for(const scenario of ['missing','mismatch']){const r=M.run(order,config,scenario);assert.equal(r.outcome,'Escalated');assert.deepEqual(r.evidence,['TRACE-208','TRACE-209']);assert.equal(r.count,3);assert.equal(r.runs.find(x=>x.run===204).status,'Escalated');}
const normal=M.run(order,config);assert.equal(normal.count,4);assert.deepEqual(normal.runs.map(x=>x.run),[204,208,209]);assert.equal(normal.runs[0].evidence.includes('VALID-01'),true);assert(normal.runs.slice(1).every(x=>!x.evidence.includes('VALID-01')));
assert.equal(M.run(order,config,'denied').count,3);assert.equal(M.run(order,config,'denied').outcome,'Escalated');
assert.equal(M.run(order,{...config,threshold:'bounded',limit:'3'}).outcome,'Recommendation ready');
for(const policy of ['adaptive','coverage']){const r=M.run(order,{...config,policy,limit:'1'});assert.equal(r.outcome,'Limit reached');assert.equal(r.runs.filter(x=>x.status==='Not investigated').length,2);assert.equal(r.runs.find(x=>x.status==='Triaged').run,policy==='adaptive'?208:204);}
const gap=M.run(order,{...config,policy:'coverage',invalid:'request',limit:'4'},'missing');assert.equal(gap.count,4);assert.equal(gap.outcome,'Escalated');assert.equal(gap.runs.filter(x=>x.status==='Triaged').length,2);assert(!gap.evidence.includes('REQUEST-01'));
for(const scenario of ['normal','missing','mismatch','denied'])for(const policy of ['adaptive','coverage'])for(const limit of ['1','2','3','4','5']){const r=M.run(order,{...config,policy,limit},scenario);assert.equal(r.events.filter(x=>x.id==='act'&&x.text.startsWith('Attempt ')).length,r.count);assert.equal(r.runs.length,3);assert(r.runs.every(x=>x.uncertainty&&x.nextOwner));for(const row of r.runs)if(row.status==='Not investigated')assert.equal(row.evidence.length,0);}
assert.deepEqual([...M.shuffle(order,()=>.2)].sort(),[...order].sort());assert.notDeepEqual(M.shuffle(order,()=>.2),order);
const original=require('../archive-01/exercise-06-agentic-loop/sources.js'),batch=require('./sources.js');for(const [id,text]of Object.entries(original))assert.equal(batch[id],text);for(const id of ['BATCH-01','BATCH-APPROVAL','TRACE-208','TRACE-209'])assert(batch[id]);
let links=0;for(const name of ['index.html','worksheet.html']){const html=fs.readFileSync(path.join(__dirname,name),'utf8');for(const [,url]of html.matchAll(/(?:href|src)="([^"]+)"/g)){if(url.startsWith('#'))continue;assert(!/^https?:|^\//.test(url));assert(fs.existsSync(path.resolve(__dirname,url)));links++;}assert(html.includes('Local simulation · No AI service connected · Nothing is sent or saved'));}cp.execFileSync(process.execPath,[path.join(__dirname,'build-worksheet.cjs'),'--check']);console.log(JSON.stringify({configurationScenarioCases:cases,controlledOutcomes:good,setupOrders:6,relativeLinks:links,checks:'Missing/misordered/unsafe blocks, return paths, authority, evidence, budgets, outcome explanations, shuffle, source parity and offline worksheet passed.'}));
module.exports={order,config};
