'use strict';
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const os = require('node:os');
const E = require('./evidence.js');
const url = file => pathToFileURL(path.resolve(__dirname,file)).href;
(async () => {
  const browser = await chromium.launch({ headless:true, ...(process.env.BROWSER_CHANNEL ? {channel:process.env.BROWSER_CHANNEL} : {}) });
  try {
    const page = await browser.newPage({viewport:{width:1440,height:900}});
    const errors=[],network=[];
    page.on('pageerror',e=>errors.push(e.message));
    page.on('request',r=>{if (/^https?:/.test(r.url())) network.push(r.url());});
    await page.goto(url('index.html'));
    await page.locator('#interactive').waitFor({state:'visible'});
    await page.locator('header a.home-link').click();
    assert.match(await page.locator('h1').innerText(),/From prompts to agentic testing workflows/);
    await page.locator('a[href="exercises/exercise-03-evidence-challenge/index.html"]').click();
    await page.locator('#interactive').waitFor({state:'visible'});
    assert.equal(await page.locator('.summary-card').count(),3);
    assert.equal(await page.locator('.source').count(),4); // three raw sources plus requirements reference
    assert.equal(await page.locator('.source[open]').count(),0);
    assert(!(await page.locator('body').innerText()).includes(E.timing));
    await page.locator('.source').first().locator('summary').click();
    assert.match(await page.locator('.source').first().innerText(),/t\+1002ms/);
    await page.locator('.source').first().locator('summary').click();
    assert(await page.locator('#review').isDisabled());
    await page.locator('#decision').focus(); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Tab');
    assert.equal(await page.evaluate(()=>document.activeElement.id),'category');
    await page.locator('#commit').click();
    assert.match(await page.locator('#commit-status').innerText(),/complete/);
    assert.equal(await page.evaluate(()=>document.activeElement.id),'commit-status');
    async function fill(action='timing') {
      for (const id of ['snapshot','association','sleep']) await page.locator(`[name="observation"][value="${id}"]`).check();
      for (const [id,value] of Object.entries({decision:'investigate',category:'synchronization',hypothesis1:'synchronization',hypothesis2:'product',action})) await page.locator('#'+id).selectOption(value);
      for (const [id,value] of Object.entries({evidenceLimit:'CI-01 shows absence at 1,002 ms, not service instability.',weakener:'A correlated reset error would weaken the timing explanation.',actionResolve:'Establish the accepted integration bound.'})) await page.locator('#'+id).fill(value);
    }
    await fill();
    await page.locator('#hypothesis2').selectOption('synchronization'); await page.locator('#commit').click();
    assert.match(await page.locator('#commit-status').innerText(),/distinct/);
    await page.locator('#hypothesis2').selectOption('product'); await page.locator('#commit').click();
    assert.equal(await page.locator('#timing-text').innerText(),E.timing);
    assert(await page.locator('#commit').isDisabled()); assert(await page.locator('#action').isDisabled());
    assert(await page.locator('#review').isEnabled()); assert(await page.locator('#revision-field').isHidden());
    assert.match(await page.locator('#record').textContent(),/INITIAL DECISION[\s\S]*Claim decision: Investigate/);
    await page.locator('#review').click();
    assert(await page.locator('#revision-field').isVisible());
    assert.match(await page.locator('#gaps').innerText(),/changed or why/);
    await page.locator('#revision').fill('Keep investigating; the cause remains unresolved.');
    assert(await page.locator('#stale').isVisible());
    await page.locator('#review').click();
    assert.match(await page.locator('#gaps').innerText(),/All required/);
    await page.locator('#decision').selectOption('reject'); await page.locator('#rejection').selectOption('healthy');
    await page.locator('#review').click(); assert.match(await page.locator('#concerns').innerText(),/healthy/);
    await page.locator('#rejection').selectOption('certainty'); await page.locator('#review').click();
    assert.match(await page.locator('#concerns').innerText(),/No modeled/);
    await page.locator('#evidenceLimit').fill('<img src=x onerror=alert(1)>');
    assert.equal(await page.locator('#record img').count(),0);
    assert.match(await page.locator('#record').textContent(),/<img/);
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copied=text;}}}));
    await page.locator('#copy').click();
    assert.equal(await page.evaluate(()=>window.copied),await page.locator('#record').textContent());
    await page.locator('#reset').click();
    assert(await page.locator('#results').isHidden()); assert(await page.locator('#record-panel').isHidden());
    assert(await page.locator('#review').isDisabled()); assert.equal(await page.locator('#timing-text').innerText(),'');
    await fill('trace'); await page.locator('#priorTiming').check(); await page.locator('#commit').click();
    assert.match(await page.locator('#commit-status').innerText(),/pending/);
    assert(await page.locator('#reveal').isHidden());
    assert.match(await page.locator('#record').textContent(),/prior reading/);
    assert(!(await page.locator('#record').textContent()).includes(E.timing));
    await page.locator('#reset').click(); await fill('patch');
    for (const id of ['independent','failure']) await page.locator(`[value="${id}"][name="observation"]`).check();
    await page.locator('#hypothesis2').selectOption('policy'); await page.locator('#decision').selectOption('accept');
    await page.locator('#commit').click(); await page.locator('#review').click();
    assert((await page.locator('#concerns li').count())>=5);
    assert(await page.locator('#reveal').isHidden());
    await page.locator('#reset').click();
    await page.screenshot({path:path.join(os.tmpdir(),'exercise-03-new-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(os.tmpdir(),'exercise-03-new-mobile.png'),fullPage:true});
    await page.setViewportSize({width:720,height:500});
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.context().setOffline(true); await page.reload(); assert(await page.locator('#interactive').isVisible());
    const noJS = await browser.newContext({javaScriptEnabled:false,offline:true});
    const fallback = await noJS.newPage(); await fallback.goto(url('index.html'));
    await fallback.locator('noscript a').first().click();
    assert.equal(await fallback.locator('.summary-card').count(),3);
    assert.equal(await fallback.locator('.source').count(),3);
    assert(!(await fallback.locator('body').innerText()).includes(E.timing));
    await fallback.emulateMedia({media:'print'});
    await fallback.screenshot({path:path.join(os.tmpdir(),'exercise-03-new-worksheet-print.png'),fullPage:true});
    await fallback.emulateMedia({media:'screen'});
    await fallback.locator('a[href="requested-evidence.html"]').click();
    await fallback.locator('summary').click(); assert((await fallback.locator('body').innerText()).includes(E.timing));
    await fallback.locator('a[href="worked-example.html"]').click(); assert.match(await fallback.locator('h1').innerText(),/One defensible/);
    assert.deepEqual(errors,[]); assert.deepEqual(network,[]);
    console.log(`Passed browser ${browser.version()}: home navigation, compact evidence, keyboard selection, commitment/reveal, feedback/revision, weak choices, copy/reset, 390/720px reflow, offline and no-JS fallback.`);
    console.log('Screenshots in '+os.tmpdir()+': exercise-03-new-{desktop,mobile,worksheet-print}.png');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
