'use strict';
(()=>{
const M=window.AgentLoop,S=window.LoopSources,$=id=>document.getElementById(id);
let run=null,challenged=null,replay=null,revision=null,handoff=null;
const value=id=>$(id).value.trim();
const setStatus=(id,msg)=>{$(id).textContent=msg;};
const lock=(id,yes)=>$(id).querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=yes);
function readDesign(){const d={};for(const [id]of M.fields)d[id]=value(id);for(const g of M.groups)d[g.id]=value(g.id);d.cap=value('cap');d.review=value('review');d.rules={};for(const [id]of M.situations)d.rules[id]={action:value('rule-'+id),why:value('why-'+id)};return d;}
function exportRecord(){if(!run)return;const draft={challengeCheckpoint:value('checkpoint'),challengeVariant:value('challenge-variant'),revisedAction:value('revised-action'),revisedWhy:value('revised-why'),revisionNote:value('revision-note'),handoff:value('conclusion')};$('record').value=M.record(run,{challenge:challenged,revision,replay,handoff,currentDraft:draft});}
function feedback(){const box=$('design-feedback');box.replaceChildren();box.hidden=false;for(const f of M.feedback(run.design)){const h=document.createElement('h3'),p=document.createElement('p');h.textContent=f.title+': '+f.choice;p.textContent=f.text;box.append(h,p);}const note=document.createElement('p');note.textContent='These explanations assess selected strategies, not your written reasoning. A person must check controller, contracts, hypotheses, branch rationales, and ending criteria.';box.append(note);}
function render(){if(!run)return;$('mission').hidden=false;$('record-panel').hidden=false;$('state-view').textContent=`Attempts ${run.count}/${run.limit} · Retained mission evidence: ${run.evidence.join(', ')||'none'} · ${run.outcome||'Investigation open'}`;const situation=M.situation(run);$('rule-view').textContent=`Your rule (${M.situations.find(x=>x[0]===situation)[1]}): ${M.actions.find(x=>x[0]===run.design.rules[situation].action)[1]}. Because: ${run.design.rules[situation].why}`;lock('action-form',!!run.outcome||run.pending!==null);$('pending').hidden=run.pending===null;if(run.pending!==null){const e=run.trace[run.pending];$('observation').textContent=e.card+'\n\n'+S[e.card];}
const list=$('trace-list');list.replaceChildren();for(const e of run.trace){const section=document.createElement('details');section.className='trace-entry';section.open=true;const h=document.createElement('summary'),p=document.createElement('p'),pre=document.createElement('pre');h.textContent=`Decision ${e.step} · ${M.actions.find(a=>a[0]===e.input.action)[1]}`;p.textContent=e.result+(e.review?' '+e.review.feedback:'');pre.textContent=JSON.stringify(e,null,2);section.append(h,p,pre);list.append(section);}
const canChallenge=run.trace.length>0&&run.pending===null;$('challenge-panel').hidden=!canChallenge;$('handoff-panel').hidden=!run.outcome;
if(!challenged){const sel=$('checkpoint'),old=sel.value;sel.replaceChildren();for(const [i,label]of [[-1,'Initial state: simulate a trace retrieval'],...run.trace.map((e,i)=>[e,i]).filter(([e])=>e.input.action==='trace'&&e.card).map(([e,i])=>[i,`Before trace decision ${e.step} (${e.before.count} attempts already used)`])]){const o=document.createElement('option');o.value=i;o.textContent=label;sel.append(o);}if([...sel.options].some(o=>o.value===old))sel.value=old;}
exportRecord();}
function guard(id,fn){try{fn();}catch(e){setStatus(id,e.message);}}
$('interactive').hidden=false;$('variant').value='normal';$('approval').value='none';
$('design-form').addEventListener('submit',e=>{e.preventDefault();guard('design-status',()=>{const d=readDesign(),errors=M.designErrors(d);if(errors.length)throw Error('Complete: '+errors.join('; '));run=M.start(d);lock('design-form',true);setStatus('design-status','Initial design committed and preserved. Apply its rules; mark deviations as design gaps.');feedback();render();$('mission-title').focus();});});
$('action-form').addEventListener('submit',e=>{e.preventDefault();guard('mission-status',()=>{run=M.dispatch(run,{action:value('action'),hypothesis:value('update'),rationale:value('reason'),gap:value('gap'),variant:value('variant')||'normal',approval:value('approval')||'none'});setStatus('mission-status',run.trace.at(-1).result);$('verdict').value='';$('validity').value='';render();if(run.pending!==null)$('verdict').focus();});});
$('observation-form').addEventListener('submit',e=>{e.preventDefault();guard('mission-status',()=>{run=M.review(run,value('verdict'),value('validity'));setStatus('mission-status',run.trace.at(-1).review.feedback);for(const id of ['update','reason','gap','action'])$(id).value='';render();});});
$('challenge-form').addEventListener('submit',e=>{e.preventDefault();guard('challenge-status',()=>{if(revision)throw Error('One revision already committed. Preserve it or reset the entire attempt.');challenged=M.challenge(run,Number(value('checkpoint')),value('challenge-variant'),run.initial);$('challenge-result').textContent=JSON.stringify(challenged,null,2);$('revision-form').hidden=false;setStatus('challenge-status','Counterfactual recorded separately. Revise the invalid-evidence rule, then replay this same checkpoint.');handoff=null;exportRecord();});});
$('revision-form').addEventListener('submit',e=>{e.preventDefault();guard('challenge-status',()=>{if(!challenged)throw Error('Challenge a checkpoint first.');if(Number(value('checkpoint'))!==challenged.checkpoint||value('challenge-variant')!==challenged.variant)throw Error('Challenge inputs changed. Submit the challenge again before revising.');if(revision)throw Error('One revision is already preserved.');if(!value('revised-action')||!value('revised-why')||!value('revision-note'))throw Error('Complete the revised rule, rationale, and handoff consequence.');revision={before:M.clone(run.design.rules.invalid),after:{action:value('revised-action'),why:value('revised-why')},note:value('revision-note')};run.design.rules.invalid=M.clone(revision.after);replay=M.challenge(run,challenged.checkpoint,challenged.variant,run.design);$('replay-result').textContent=JSON.stringify(replay,null,2);lock('revision-form',true);lock('challenge-form',true);setStatus('challenge-status','Revision and replay preserved. Original trace, evidence, and action count are unchanged.');render();});});
$('handoff-form').addEventListener('submit',e=>{e.preventDefault();guard('handoff-status',()=>{if(!run.outcome)throw Error('Choose an ending first.');if(!revision)throw Error('Complete a separate challenge, revision, and replay before the final handoff.');if(!value('conclusion'))throw Error('Record recommendation or unresolved question with evidence, uncertainty, and next human action.');handoff={outcome:run.outcome,text:value('conclusion'),reviewer:run.design.reviewer,count:run.count};setStatus('handoff-status','Final handoff recorded. Ask a person to review the reasoning; no real patch or learner competence has been verified.');exportRecord();});});
$('conclusion').addEventListener('input',()=>{if(handoff)setStatus('handoff-status','Draft changed. Recorded handoff is stale until recorded again.');exportRecord();});
for(const id of ['challenge-form','revision-form'])$(id).addEventListener('input',()=>{if(challenged&&!revision)setStatus('challenge-status','Draft changed. Challenge feedback describes the last submitted checkpoint; submit the challenge again if its inputs changed.');exportRecord();});
$('copy').addEventListener('click',async()=>{exportRecord();try{await navigator.clipboard.writeText($('record').value);setStatus('copy-status','Record copied.');}catch{$('record').focus();$('record').select();setStatus('copy-status','Clipboard unavailable. The complete record is selected; press Ctrl+C (or use your device copy command).');}});
$('reset-attempt').addEventListener('click',()=>{run=challenged=replay=revision=handoff=null;document.querySelectorAll('form').forEach(f=>{lock(f.id,false);HTMLFormElement.prototype.reset.call(f);});for(const id of ['mission','pending','challenge-panel','revision-form','handoff-panel','record-panel','design-feedback'])$(id).hidden=true;for(const id of ['design-status','mission-status','challenge-status','handoff-status','copy-status','challenge-result','replay-result','trace-list'])$(id).textContent='';$('record').value='';$('variant').value='normal';$('approval').value='none';$('goal').focus();});
})();
