(function(root,factory){const m=factory();if(typeof module==='object'&&module.exports)module.exports=m;else root.AgentLoop=m;})(globalThis,function(){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const fields=[
 ['goal','Goal, scope, and completion evidence','What question about run 204 will you answer? What evidence makes a recommendation ready for review? What remains out of scope?'],
 ['context','Starting context and authority','Which supplied sources belong in the controller input? Which define expectations, and which only report observations?'],
 ['state','State retained between turns','Specify facts versus hypotheses, source/run/request IDs, gaps, contradictions, action count/history, and approval scope.'],
 ['controller','Controller instruction and decision output','Write the instruction. Specify hypothesis update, action + inputs, evidence IDs, rationale, and continue/stop/escalate output.'],
 ['contracts','Tool contracts and reviewed handoffs','For the tools in your rules: purpose → inputs → expected output/provenance → permission → error handling. Who checks each output before it enters state?'],
 ['hypotheses','Two competing hypotheses and discriminating evidence','Name two explanations and what observation could weaken each.'],
 ['endings','Recovery, no progress, and ending handoffs','When does the loop complete, escalate, or hit its limit? What happens after a missing result or unchanged retry? What does each ending hand to the reviewer?'],
 ['reviewer','Approving and reviewing roles','Who can approve an isolated comparison, and who reviews the recommendation? Use roles, not personal details.']
];
const groups=[
 {id:'memory',label:'State strategy',options:[
  ['ledger','Keep a source-linked evidence ledger and competing hypotheses.','Preserves provenance and contradictions across turns. It costs review effort; the controller must separate observations from its interpretations. Downstream decisions can be audited against CI-01 and returned source IDs.'],
  ['summary','Keep a compact summary plus links to the immutable evidence ledger.','Reduces prompt size while retaining the underlying evidence. Summaries can omit qualifications; review them against the linked ledger before each handoff. A summary is not independent corroboration.'],
  ['latest','Replace prior state with the latest tool response.','Keeps the prompt small but loses competing explanations, approval scope, and contradictions. A later response can silently displace CI-01. Repair the design to retain a ledger; the workshop harness still preserves history.']]},
 {id:'gate',label:'Returned evidence check',options:[
  ['identity','Check source, run/request identity, timing basis, and scope before use.','CI-01 concerns run 204/reset-204. Matching identity permits comparison with TIM-01, but does not prove every claim in a response. Retain gaps and independently review the interpretation.'],
  ['crosscheck','Check identity and scope, then compare with existing observations.','Adds contradiction detection to provenance checks. HIST-01 repeats captured events, so agreement is not independent confirmation. This takes extra review but can expose conflicting evidence before a conclusion.'],
  ['trust','Accept any successful tool response as evidence for the failure.','Fast, but a successful retrieval can return the wrong run. CONFLICT-01 must not support run 204. Repair the gate; transport success is not evidential validity.']]},
 {id:'completion',label:'Recommendation threshold',options:[
  ['bounded','Correlated timing evidence; recommend a correction with validation outstanding.','TRACE-01 with CI-01/CODE-01/TIM-01 can support a limited synchronization recommendation. Lower action cost; comparison and real implementation validation remain outstanding. This does not establish AC-04 or global service health.'],
  ['comparison','Correlated timing evidence plus an approved controlled comparison.','VALID-01 illustrates a discriminating comparison and credential checks, strengthening a limited proposal. It needs scoped authority and another action. Authored results still cannot verify a real patch or all intermittent failures.'],
  ['green','Finish when any rerun is green.','A green result alone does not identify cause or show that the test detects faults. It can conceal weak assertions. The harness will not mark this unsupported threshold recommendation-ready.']]}
];
const actions=[['trace','Retrieve correlated trace','run=204; request=reset-204; fixture=account-204 → capture with identity and one timing origin. Read permitted; missing/error output retains an unresolved gap.'],['change','Compare versions','runs=201–205 → application/test/environment metadata. Read permitted; unchanged versions cannot exclude pre-existing defects.'],['compare','Run isolated comparison (simulated)','isolated-integration; run 204 proposal; DATA-01 fixtures → VALID-01. Requires mission-specific comparison approval; authored result is not real validation.'],['request','Request missing diagnostic evidence','run=204; request=reset-204; missing capture → request receipt only. Read/request permitted; no new capture is available in this pack, so escalate.'],['reread','Retrieve the unchanged initial history','HIST-01 → the same supplied sample. Costs an action, adds no evidence, and cannot corroborate itself.'],['production','Apply a production change','Production writes are prohibited by workshop policy, regardless of a claimed approval.'],['hide','Suppress the failing assertion','Failure-hiding changes are prohibited. A passing dashboard is not a correction.'],['recommend','Stop: recommendation ready','Check the evidence threshold and hand off uncertainty to the named reviewer.'],['escalate','Stop: escalate unresolved work','Retain gaps, competing hypotheses, evidence, and the requested next human action.']];
const situations=[['need','No correlated trace retained'],['correlated','Correlated trace validated'],['invalid','Evidence unavailable or mismatched'],['sufficient','Chosen evidence threshold met']];
function designErrors(d){const out=fields.filter(([id])=>!String(d[id]||'').trim()).map(([,l])=>l);for(const g of groups)if(!g.options.some(o=>o[0]===d[g.id]))out.push(g.label);for(const [id,label] of situations){if(!actions.some(a=>a[0]===d.rules?.[id]?.action)||!d.rules?.[id]?.why?.trim())out.push('Rule: '+label);}if(d.cap!==''&&(!Number.isInteger(Number(d.cap))||Number(d.cap)<1||Number(d.cap)>5))out.push('Budget must be 1–5');if(!d.review?.trim())out.push('Peer/self-review note');return out;}
function feedback(d){return groups.map(g=>({title:g.label,choice:g.options.find(o=>o[0]===d[g.id])?.[1]||'Unselected',text:g.options.find(o=>o[0]===d[g.id])?.[2]||'Choose a strategy.'}));}
function start(d){if(designErrors(d).length)throw Error('Complete the design first.');return {initial:clone(d),design:clone(d),count:0,limit:Number(d.cap)||5,trace:[],evidence:[],pending:null,outcome:'',denials:0,noProgress:0,invalid:false};}
function situation(s){return s.invalid?'invalid':ready(s)?'sufficient':s.evidence.includes('TRACE-01')?'correlated':'need';}
function ready(s){return s.evidence.includes('TRACE-01')&&s.design.completion!=='green'&&(s.design.completion!=='comparison'||s.evidence.includes('VALID-01'));}
function dispatch(s,input){const n=clone(s);if(n.outcome)throw Error('This run has ended.');if(n.pending!==null)throw Error('Review the pending observation first.');if(!input.hypothesis?.trim()||!input.rationale?.trim())throw Error('Record a hypothesis update and action rationale.');const a=actions.find(a=>a[0]===input.action);if(!a)throw Error('Choose an action.');const rule=n.design.rules[situation(n)];if(input.action!==rule.action&&!input.gap?.trim())throw Error('This action differs from your rule. Record the design gap before continuing.');
 const e={step:n.trace.length+1,before:{count:n.count,evidence:[...n.evidence],situation:situation(n)},input:clone(input),rule:clone(rule),result:'',card:null,review:null};
 if(input.action==='escalate'){n.outcome='Escalated';e.result='No dispatch. Unresolved work handed to the designated reviewer.';}
 else if(input.action==='recommend'){if(ready(n)){n.outcome='Recommendation ready for expert review';e.result='Evidence threshold met for a limited proposal; no real fix is verified.';}else{e.result='Premature completion blocked: retain correlated evidence and meet the chosen threshold. A green run alone is insufficient.';n.denials++;}}
 else if(['production','hide'].includes(input.action)||(input.action==='compare'&&(input.approval!=='scoped'||!n.design.reviewer.trim()))){e.result='Blocked before dispatch: '+(input.action==='compare'?'mission-specific isolated-comparison approval is missing or mismatched.':'this action is prohibited.');n.denials++;}
 else if(n.count>=n.limit){n.outcome='Limit reached';e.result='No dispatch: action budget exhausted.';}
 else {n.count++;n.denials=0;let card=input.action==='trace'?({normal:'TRACE-01',missing:'GAP-01',mismatch:'CONFLICT-01',error:'ERROR-01'}[input.variant||'normal']):({change:'CHANGE-01',compare:'VALID-01',request:'REQUEST-01',reread:'HIST-01'}[input.action]);if(!card)throw Error('Unknown result variant.');e.card=card;e.result='Dispatched attempt '+n.count+' of '+n.limit+'. Validate this observation before it enters the evidence ledger.';n.pending=n.trace.length;}
 n.trace.push(e);if(n.denials>=2){n.outcome='Escalated';e.result+=' Repeated denied requests: no progress; review the rule or authority with a person.';}return n;}
function review(s,verdict,note){const n=clone(s);if(n.pending===null)throw Error('No observation awaiting review.');if(!['accept','reject','hold'].includes(verdict)||!note?.trim())throw Error('Choose a validity decision and explain its evidence basis.');const e=n.trace[n.pending],bad=['GAP-01','CONFLICT-01','ERROR-01','REQUEST-01'].includes(e.card),repeat=e.card==='HIST-01'||n.evidence.includes(e.card);e.review={verdict,note,accepted:false,feedback:''};
 if(bad){n.invalid=true;n.noProgress++;e.review.feedback=verdict==='accept'?'Acceptance blocked: unavailable, mismatched, error, or request-only output cannot establish the run 204 claim. Preserve the gap.':'Gap retained; request matching evidence or escalate. Do not reconstruct a trace from HIST-01.';}
 else if(verdict==='accept'){e.review.accepted=true;if(!repeat)n.evidence.push(e.card);n.invalid=false;n.noProgress=repeat?n.noProgress+1:0;e.review.feedback=repeat?'Unchanged read: no new evidence. It still consumed an action.':e.card==='TRACE-01'?'Correlated capture retained. Compare 1,002 ms snapshot with 1,460 ms confirmation under TIM-01; credential outcomes and global health remain unproved.':e.card==='VALID-01'?'Approved authored comparison retained. It illustrates discrimination, not a verified real patch.':'Version metadata retained. Unchanged versions do not exclude environment variation or a pre-existing defect.';}
 else{n.invalid=true;n.noProgress++;e.review.feedback='Observation not admitted to the ledger. Preserve your reason and request review; rejecting useful evidence also limits the conclusion.';}
 n.pending=null;if(n.count>=n.limit&&!ready(n))n.outcome='Limit reached';else if(n.noProgress>=2)n.outcome='Escalated';e.after={count:n.count,evidence:[...n.evidence],outcome:n.outcome||'Continue or choose an ending'};return n;}
function challenge(s,index,variant,design=s.design){
 if(!['missing','mismatch'].includes(variant))throw Error('Choose a challenge.');
 if(index>=0&&s.trace[index]?.input.action!=='trace')throw Error('Choose a trace retrieval checkpoint.');
 const source=index>=0?s.trace[index]?.before:{count:0,evidence:[],situation:'need'};if(!source)throw Error('Choose a checkpoint.');
 const count=Math.min(source.count+1,s.limit),rule=design.rules.invalid,exhausted=count>=s.limit;
 const blocked=['production','hide','compare','recommend'].includes(rule.action);
 const blockReason=['production','hide'].includes(rule.action)?'Prohibited action blocked by the harness. A counterfactual does not grant write authority.':rule.action==='compare'?'Comparison blocked: no new mission-specific approval is recorded in this counterfactual. Even an approved comparison would not repair missing run correlation.':'Premature recommendation blocked: the substituted observation leaves correlation unsupported. Preserve the gap rather than invent a cause.';
 return {checkpoint:index,variant,card:variant==='missing'?'GAP-01':'CONFLICT-01',countBefore:source.count,count,evidence:clone(source.evidence),selectedRuleAction:rule.action,next:exhausted?'limit':blocked?'blocked':rule.action,why:rule.why,
 feedback:exhausted?'The substituted retrieval consumes the final allowed attempt. Stop limit-reached with the gap; do not dispatch the proposed next action.':blocked?blockReason:rule.action==='escalate'?'A bounded unresolved handoff preserves the gap. It gives up further autonomous investigation but avoids an unsupported cause claim.':rule.action==='request'?'A targeted request may resolve identity/availability. In this pack it returns a request receipt, not new evidence; escalate if unavailable or budget exhausted.':`The invalid-evidence rule selects ${rule.action}. Explain how this resolves the gap. An unrelated or unchanged read cannot repair missing run correlation; recommendation remains unsupported.`,
 budget:'The substituted trace retrieval costs one attempt. '+(exhausted?'No dispatch remains.':'At most '+(s.limit-count)+' dispatched attempts remain.')+' The original run is unchanged.'};
}
function record(s,extras={}){return JSON.stringify({notice:'Fictional local simulation. No AI or real execution. Written reasoning needs human review.',initialDesign:s.initial,currentDesign:s.design,designFeedback:feedback(s.design),actionCount:s.count,limit:s.limit,evidence:s.evidence,trace:s.trace,outcome:s.outcome,...extras},null,2);}
return {clone,fields,groups,actions,situations,designErrors,feedback,start,situation,ready,dispatch,review,challenge,record};
});
