'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path'),os=require('node:os'),M=require('./model.js');
const url=n=>pathToFileURL(path.join(__dirname,n)).href;
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});try{
const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),errors=[],network=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await p.goto(url('index.html'));assert(await p.locator('#interactive').isVisible());assert(await p.locator('#mission').isHidden());await p.locator('#commit').click();assert.match(await p.locator('#design-status').innerText(),/Complete/);
async function design(cap='3',threshold='comparison'){for(const [id]of M.fields)await p.locator('#'+id).fill('Review '+id+' against CI-01, TIM-01, AC-04; retain uncertainty. <b>literal</b>');for(const [id,v]of Object.entries({memory:'ledger',gate:'identity',completion:threshold,cap,review:'A peer checked the branches, handoffs, and stopping conditions.'})){if(id==='review')await p.locator('#'+id).fill(v);else await p.locator('#'+id).selectOption(v);}for(const [id,a]of [['need','trace'],['correlated','compare'],['invalid','recommend'],['sufficient','recommend']]){await p.locator('#rule-'+id).selectOption(a);await p.locator('#why-'+id).fill('Seek matching evidence; expose this rule if unsupported.');}await p.locator('#commit').click();assert(await p.locator('#goal').isDisabled());}
async function action(a,approval='none',variant='normal'){await p.locator('#update').fill('CI-01 snapshot alone leaves timing race and service failure competing.');await p.locator('#action').selectOption(a);await p.locator('#reason').fill('Resolve this uncertainty with correlated evidence.');await p.locator('#gap').fill('This proposed action addresses a recorded gap in the initial rule.');await p.locator('#approval').selectOption(approval);await p.locator('#variant').selectOption(variant);await p.locator('#action-form button').click();}
async function review(v='accept'){await p.locator('#verdict').selectOption(v);await p.locator('#validity').fill('Checked run/request and scope. Preserve limitations.');await p.locator('#observation-form button').click();}
await p.screenshot({path:path.join(os.tmpdir(),'exercise-06-desktop.png'),fullPage:true});await design();await action('trace');assert.match(await p.locator('#observation').innerText(),/TRACE-01/);assert.match(await p.locator('#state-view').innerText(),/evidence: none/);assert(await p.locator('#action').isDisabled());await review();await action('compare','prior');assert.match(await p.locator('#mission-status').innerText(),/Blocked/);assert(await p.locator('#pending').isHidden());assert.match(await p.locator('#state-view').innerText(),/Attempts 1\/3/);await action('compare','scoped');assert.match(await p.locator('#observation').innerText(),/VALID-01/);await review();await action('recommend');assert.match(await p.locator('#state-view').innerText(),/Recommendation ready/);
await p.locator('#checkpoint').selectOption('0');await p.locator('#challenge-variant').selectOption('mismatch');await p.locator('#challenge-form button').click();assert.match(await p.locator('#challenge-result').innerText(),/unsupported/);const pre=JSON.parse(await p.locator('#record').inputValue());await p.locator('#revised-action').selectOption('escalate');await p.locator('#revised-why').fill('Wrong run cannot establish this cause; ask test owner.');await p.locator('#revision-note').fill('Check identity before admitting evidence and handing off.');await p.locator('#challenge-variant').selectOption('missing');await p.locator('#revision-form button').click();assert.match(await p.locator('#challenge-status').innerText(),/inputs changed/);await p.locator('#challenge-variant').selectOption('mismatch');await p.locator('#revision-form button').click();assert.match(await p.locator('#replay-result').innerText(),/bounded unresolved/);const post=JSON.parse(await p.locator('#record').inputValue());assert.deepEqual(pre.trace,post.trace);assert.equal(pre.actionCount,post.actionCount);assert.equal(post.initialDesign.rules.invalid.action,'recommend');assert.equal(post.currentDesign.rules.invalid.action,'escalate');await p.locator('#conclusion').fill('TRACE-01 / TIM-01 support a timing race in run 204. VALID-01 is authored. Reviewer must validate the real patch; service health remains unknown.');await p.locator('#handoff-form button').click();assert.match(await p.locator('#handoff-status').innerText(),/recorded/);await p.locator('#conclusion').fill('Changed draft');assert.match(await p.locator('#handoff-status').innerText(),/stale/);
await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied');}}}));await p.locator('#copy').click();assert.match(await p.locator('#copy-status').innerText(),/Clipboard unavailable/);await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copied=text;}}}));await p.locator('#copy').click();assert.match(await p.locator('#copy-status').innerText(),/copied/);assert((await p.evaluate(()=>window.copied)).includes('<b>literal</b>'));assert.equal(await p.locator('#design-feedback b').count(),0);
await p.locator('#handoff-panel').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(os.tmpdir(),'exercise-06-handoff.png')});await p.screenshot({path:path.join(os.tmpdir(),'exercise-06-completed.png'),fullPage:true});await p.locator('#reset-attempt').click();assert(await p.locator('#mission').isHidden());assert.equal(await p.locator('#goal').inputValue(),'');await design('1');await action('trace');await review();assert.match(await p.locator('#state-view').innerText(),/Limit reached/);
await p.locator('#reset-attempt').click();await design();await action('trace','none','mismatch');await review();assert.match(await p.locator('#mission-status').innerText(),/Acceptance blocked/);assert.match(await p.locator('#state-view').innerText(),/evidence: none/);await action('escalate');assert.match(await p.locator('#state-view').innerText(),/Escalated/);
await p.locator('#reset-attempt').click();await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(os.tmpdir(),'exercise-06-mobile.png'),fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('#memory').focus();await p.keyboard.press('ArrowDown');assert.equal(await p.locator('#memory').inputValue(),'ledger');await p.setViewportSize({width:720,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
await p.goto(url('worksheet.html'));await p.emulateMedia({media:'print'});await p.pdf({path:path.join(os.tmpdir(),'exercise-06-worksheet.pdf'),format:'A4',printBackground:true});await p.screenshot({path:path.join(os.tmpdir(),'exercise-06-print.png'),fullPage:true});
const offline=await browser.newContext({javaScriptEnabled:false,offline:true}),q=await offline.newPage();await q.goto(url('index.html'));assert(await q.locator('noscript').isVisible());await q.locator('noscript a').click();assert.match(await q.title(),/worksheet/);await q.getByRole('link',{name:/Separate result cards/}).click();await q.locator('#CONFLICT-01 summary').click();assert.match(await q.locator('#CONFLICT-01').innerText(),/run=207/);await p.emulateMedia({media:'screen'});await p.goto(url('index.html'));assert.match(await p.title(),/Design an agentic AI loop/);assert(await p.locator('#interactive').isVisible());assert.equal(errors.length,0,errors.join('\n'));assert.equal(network.length,0);console.log(JSON.stringify({browser:browser.version(),checks:'Full route, authority, invalid evidence, cap, challenge/revision history, stale draft, copy fallback, reset, literal text, keyboard, reflow, no-JS/offline and print export passed.',screenshots:os.tmpdir()}));await context.close();await offline.close();
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
