'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),M=require('./model.js'),S=require('./sources.js');
function design(over={}){return {...Object.fromEntries(M.fields.map(([id])=>[id,'Written rationale to review: '+id])),memory:'ledger',gate:'identity',completion:'bounded',cap:'5',review:'Peer checks identity, authority, endings.',rules:{need:{action:'trace',why:'Resolve run identity'},correlated:{action:'compare',why:'Discriminate weak test'},invalid:{action:'escalate',why:'Preserve unresolved identity'},sufficient:{action:'recommend',why:'Hand off the bounded recommendation'}},...over};}
function input(action,over={}){return {action,hypothesis:'Timing race versus late completion; CI-01 alone is insufficient.',rationale:'Seek discriminating evidence.',gap:'Documented policy gap when this differs from the chosen rule.',approval:'none',variant:'normal',...over};}
function step(s,a,over={},verdict='accept'){let n=M.dispatch(s,input(a,over));return n.pending===null?n:M.review(n,verdict,'Check source/run/request/clock and preserve uncertainty.');}
let combinations=0;
for(const memory of M.groups[0].options.map(x=>x[0]))for(const gate of M.groups[1].options.map(x=>x[0]))for(const completion of ['bounded','comparison','green'])for(const cap of ['','1','2','3','4','5'])for(const variant of ['normal','missing','mismatch','error']){
 const d=design({memory,gate,completion,cap}),s=M.start(d),before=JSON.stringify(s),n=step(s,'trace',{variant});assert.equal(JSON.stringify(s),before,'Pure transitions');assert.equal(n.count,1);assert.equal(n.evidence.includes('TRACE-01'),variant==='normal');assert(n.limit<=5);if(cap==='1'&&!M.ready(n))assert.equal(n.outcome,'Limit reached');if(variant!=='normal')assert(!M.ready(n));assert.equal(M.feedback(d).length,3);for(const f of M.feedback(d))assert(f.text.length>80);if(memory==='latest')assert.match(M.feedback(d)[0].text,/loses/);if(gate==='trust')assert.match(M.feedback(d)[1].text,/wrong run/);if(completion==='green')assert.match(M.feedback(d)[2].text,/unsupported threshold/);combinations++;
}
for(const approval of ['none','prior','wrong','scoped'])for(const a of ['compare','production','hide']){const s=M.start(design()),n=M.dispatch(s,input(a,{approval}));const allowed=a==='compare'&&approval==='scoped';assert.equal(n.count,allowed?1:0);assert.equal(n.pending!==null,allowed);assert.equal(n.trace[0].card,allowed?'VALID-01':null);}
assert(M.designErrors(design({cap:'99'})).length);assert(M.designErrors(design({goal:''})).length);
let s=M.start(design({completion:'comparison',cap:'2'}));assert.throws(()=>M.dispatch(s,input('change',{gap:''})),/design gap/);s=step(s,'trace');s=step(s,'compare',{approval:'scoped'});assert(M.ready(s));s=step(s,'recommend');assert.match(s.outcome,/Recommendation ready/);assert.equal(s.count,2);assert.throws(()=>step(s,'trace'),/ended/);
let weak=step(M.start(design({completion:'green'})),'trace');weak=step(weak,'compare',{approval:'scoped'});assert(!M.ready(weak));weak=step(weak,'recommend');assert.match(weak.trace.at(-1).result,/Premature/);assert.equal(weak.count,2);
let denied=step(M.start(design()),'compare');denied=step(denied,'compare');assert.equal(denied.outcome,'Escalated');assert.equal(denied.count,0);
let repeated=step(M.start(design()),'reread');repeated=step(repeated,'reread');assert.equal(repeated.outcome,'Escalated');assert.equal(repeated.count,2);assert.deepEqual(repeated.evidence,[]);
let pending=M.dispatch(M.start(design()),input('trace'));assert.throws(()=>M.dispatch(pending,input('change')),/pending/);assert.throws(()=>M.review(pending,'accept',''),/explain/);let held=M.review(pending,'hold','Need source review.');assert(!held.evidence.includes('TRACE-01'));
let mismatch=step(M.start(design()),'trace',{variant:'mismatch'});assert.match(mismatch.trace[0].review.feedback,/Acceptance blocked/);mismatch=step(mismatch,'request');assert.equal(mismatch.outcome,'Escalated');assert.equal(mismatch.count,2);
const before=JSON.stringify(s),c=M.challenge(s,0,'mismatch'),revised=M.clone(s.design);revised.rules.invalid={action:'request',why:'Request the correct run capture'};const replay=M.challenge(s,0,'mismatch',revised);assert.equal(JSON.stringify(s),before);assert.deepEqual(c.evidence,replay.evidence);assert.equal(c.count,replay.count);assert.notEqual(c.next,replay.next);assert.match(replay.feedback,/receipt/);
assert(S['TRACE-01'].includes('run=204 request=reset-204'));assert(S['CONFLICT-01'].includes('run=207'));assert(S['VALID-01'].includes('old-password-still-valid'));
const limited=M.start(design({cap:'1'})),lastChallenge=M.challenge(limited,-1,'missing');assert.equal(lastChallenge.count,1);assert.equal(lastChallenge.next,'limit');assert.equal(limited.count,0);assert.throws(()=>M.challenge(s,1,'missing'),/trace retrieval/);
for(const a of ['production','hide','compare','recommend']){const d=design();d.rules.invalid.action=a;assert.equal(M.challenge(M.start(d),-1,'mismatch').next,'blocked');}
let transitions=0;
function explore(state,depth){if(!depth||state.outcome)return;for(const [a,approval,variant]of [['trace','none','normal'],['trace','none','missing'],['trace','none','mismatch'],['trace','none','error'],['change','none','normal'],['compare','none','normal'],['compare','scoped','normal'],['reread','none','normal'],['recommend','none','normal'],['escalate','none','normal']]){const n=step(state,a,{approval,variant});assert(n.count<=n.limit);assert(n.count>=state.count);assert.equal(n.pending,null);assert(!n.evidence.includes('CONFLICT-01'));assert(!n.evidence.includes('GAP-01'));if(n.outcome.startsWith('Recommendation'))assert(M.ready(n));if(n.trace.at(-1).card==='VALID-01')assert.equal(approval,'scoped');transitions++;explore(n,depth-1);}}
for(const cap of ['1','2','5'])for(const completion of ['bounded','comparison','green'])explore(M.start(design({cap,completion})),3);
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');assert(!html.includes('t+1460ms'));assert(!html.includes('With isolated fixtures and controlled confirmation delays'));assert(html.includes('Local simulation · No AI service connected · Nothing is sent or saved'));
let links=0;for(const file of fs.readdirSync(__dirname).filter(x=>x.endsWith('.html'))){const body=fs.readFileSync(path.join(__dirname,file),'utf8');for(const [,url]of body.matchAll(/(?:href|src)="([^"]+)"/g)){if(url.startsWith('#'))continue;assert(!/^(https?:|\/)/.test(url),'Must be local relative asset: '+url);assert(fs.existsSync(path.resolve(__dirname,decodeURIComponent(url.split('#')[0]))),`${file} -> ${url}`);links++;}}
cp.execFileSync(process.execPath,[path.join(__dirname,'build-pages.cjs'),'--check']);
console.log(JSON.stringify({designVariantCombinations:combinations,authorityCombinations:12,transitions,relativeLinks:links,checks:'State, source parity, reveals, review gates, cap, no-progress, endings, pure counterfactual, explanations and generated parity passed.'}));
module.exports={design,input};
