'use strict';
const fs=require('node:fs'),path=require('node:path'),M=require('./review.js');
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const page=(title,body,interactive=false)=>`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>E5 · ${esc(title)}</title><link rel="icon" href="../../shared/favicon.ico"><link rel="stylesheet" href="../../shared/theme.css"><link rel="stylesheet" href="../../shared/styles.css"><link rel="stylesheet" href="../../shared/forms.css"><link rel="stylesheet" href="styles.css">${interactive?'<script defer src="review.js"></script><script defer src="app.js"></script>':''}<link rel="stylesheet" href="../../shared/navigation.css"></head><body>
<a class="skip-link" href="#task-title">Skip to exercise</a><header class="topbar page-header"><div class="header-heading"><a class="home-icon" href="../../index.html" aria-label="Home" title="Home"><img src="../../shared/home.svg" alt="" width="24" height="24"></a><span class="page-title">${esc(title)}</span></div><nav class="exercise-nav" aria-label="Tutorial navigation">${interactive ? '' : '<a class="home-link" href="index.html">Back to exercise</a>'}<a class="home-link requirements-link" href="../../requirements.html">All requirements</a><a class="home-link glossary-link" href="../../glossary.html">Glossary</a><div class="header-actions">${interactive ? '<button id="reset-attempt" class="header-reset" type="button">Reset</button>' : ''}<span class="badge">SEETEST 2026 / TUTORIAL<span class="header-page-label">EXERCISE 05</span></span></div></nav></header><main>
<section class="intro"><div class="eyebrow">AUTOMATION REVIEW / TOOLS &amp; PERMISSIONS</div><h1 id="task-title" tabindex="-1">${esc(title)}</h1><p>Review a proposed change, plan checks that could expose faults, and judge an assigned action.</p><div class="notice"><span class="dot" aria-hidden="true"></span>${esc(M.notice)}</div></section>
${body}<footer>From Prompts to Agentic Testing Workflows <span>Review → validation → authority</span></footer></main></body></html>\n`;
const sourceDetails=M.sources.map(source=>`<details class="source"><summary>${esc(source.id)} · ${esc(source.title)}</summary><p class="metadata">${esc(source.owner)}</p><${source.code?'pre':'p'} class="source-text">${esc(source.text)}</${source.code?'pre':'p'}>${source.note?`<p class="field-note">${esc(source.note)}</p>`:''}</details>`).join('\n');
const brief=`<section class="card brief"><div class="eyebrow">YOUR TASK</div><p><strong>Review three concerns, plan three validation cases, then decide authority.</strong> You have one assigned action request and approval record; you do not choose the situation.</p><p><strong>Handoff:</strong> The regression proposal prioritizes credential protection. Supported expectations and setup conditions need review. Earlier saved work is not needed.</p><p class="field-note">The classroom slot is 17 minutes. Work individually or in pairs. This is an authored local simulation; no code or test runs.</p></section>`;
const radio=(name,options)=>options.map(option=>`<label class="choice"><input type="radio" name="${esc(name)}" value="${esc(option.id)}"><span>${esc(option.label)}</span></label>`).join('');
const textArea=(id,label,placeholder)=>`<label for="${id}">${esc(label)}</label><textarea id="${id}" name="${id}" rows="2" maxlength="800" placeholder="${esc(placeholder)}"></textarea>`;
const concernFields=M.groups.map(group=>`<fieldset class="concern"><legend>${esc(group.title)}</legend><p class="source-excerpt"><strong>Relevant sources · ${esc(group.source)}</strong><br>${esc(group.excerpt)}</p><div class="choice-grid">${radio(group.id,group.options)}</div></fieldset>`).join('\n');
const faultFields=M.faults.map(fault=>`<div class="fault-card" data-fault="${fault.id}"><label class="choice fault-selector"><input type="checkbox" name="faultIds" value="${fault.id}"><span><strong>${esc(fault.title)}</strong><span class="expected">${esc(fault.condition)} <small>[${esc(fault.source)}]</small></span></span></label><fieldset class="fault-outcomes" hidden disabled><legend>Expected outcome and evidence · ${esc(fault.title)}</legend>${radio('faultOutcome_'+fault.id,fault.outcomes)}</fieldset></div>`).join('\n');
const policy=`<section class="policy"><h3>Workshop authority policy</h3><p>${esc(M.policy)}</p><p class="field-note">The request and approval below are hypothetical teaching records. Even an allowed decision does not apply code, run a comparison, or accept the patch.</p></section>`;
const form=`<form id="builder" novalidate><div class="step-nav" aria-label="Review stages"><button type="button" data-step="0" aria-current="step">1 · Review proposal</button><button type="button" data-step="1">2 · Design validation</button><button type="button" data-step="2">3 · Decide authority</button></div>
<section class="step card" data-panel="0"><div class="eyebrow">01 / REVIEW THREE CONCERNS</div><h2 tabindex="-1">Review the proposal</h2><p>The proposed wait, credential checks, and policy test need separate treatments. Use the nearby excerpts; open the full sources when needed.</p>${concernFields}${textArea('rationale','One brief source-based explanation','Name the source IDs, why you retained or changed the proposal, and an unresolved question.')}<button class="primary next" type="button" data-step="1">Next: validation →</button></section>
<section class="step card" data-panel="1" hidden><div class="eyebrow">02 / ONE VALID SUCCESS + TWO FAULTS</div><h2 tabindex="-1">Design validation</h2><p>These are proposed checks, not execution results. Choose the expected outcome and observation for the delayed valid success, then choose exactly two different deliberately faulty cases.</p><fieldset class="concern"><legend>${esc(M.success.title)} · required</legend><p class="source-excerpt">${esc(M.success.condition)} <small>[${esc(M.success.source)}]</small></p>${radio('successOutcome',M.success.outcomes)}</fieldset><fieldset><legend>Choose two faulty cases</legend><p id="fault-help" class="field-note" role="status">0 of 2 selected. Choose two different faults.</p>${faultFields}</fieldset><div class="actions"><button class="text-button" type="button" data-step="0">← Proposal</button><button class="primary next" type="button" data-step="2">Next: authority →</button></div></section>
<section class="step card" data-panel="2" hidden><div class="eyebrow">03 / JUDGE THE ASSIGNED ACTION</div><h2 tabindex="-1">Decide authority and disposition</h2>${policy}<section class="assigned-card" aria-label="Your assigned action and approval"><h3>Assigned card <span id="card-id">A</span></h3><p><strong>Action request:</strong> <span id="request-text"></span></p><p><strong>Approval record:</strong> <span id="approval-text"></span></p></section><fieldset><legend>Decision on this request</legend>${radio('decision',M.decisions)}</fieldset>${textArea('permissionReason','Why allow, block, or defer?','Name the action, approval scope, prohibition, or technical prerequisite that matters.')}<p class="field-note">A review-ready proposal, authority for one action, and acceptance after validation are different. Written reasons need human review.</p><div class="actions"><button class="text-button" type="button" data-step="1">← Validation</button><button id="commit" class="primary" type="submit">Commit initial review</button></div></section><p id="status" role="status" tabindex="-1"></p></form>`;
const index=page('Review an automation change',`${brief}<p class="resource-links"><a id="worksheet-link" href="worksheet-A.html">Worksheet for assigned card</a> · <a href="workflow-template.md" download>Editable review template</a></p><noscript><p class="card">JavaScript is off. Use the worksheet link for the default card, or the specific assigned worksheet link supplied by your facilitator. The worksheet includes the full sources and separate feedback instructions.</p></noscript><div class="workspace"><aside class="card reference"><h2>Prepared proposal and full sources</h2><p class="field-note">The patch is authored teaching material, not an approved implementation.</p><section class="proposal"><h3>Proposal for review</h3><pre>${esc(M.proposal)}</pre><p class="field-note">These line numbers belong to the proposal, not CODE-01.</p></section><h3>Expand the full source records</h3>${sourceDetails}</aside><div id="interactive" hidden>${form}</div></div>
<section id="results" class="card" hidden><div class="eyebrow">REVIEW AFTER COMMITMENT</div><h2 id="results-title" tabindex="-1">Your review feedback</h2><p>Prepared feedback checks modeled choices. It cannot assess the meaning of your written reasons or prove that validation ran.</p><p id="stale" class="warning" hidden>Your draft changed. This feedback describes the last committed review until you commit the revision.</p><h3 id="technical-result"></h3><p id="permission-result" class="outcome"></p><p id="permission-concern" class="warning" hidden></p><div id="explanations"></div><h3>Outstanding conditions for later acceptance</h3><ul id="outstanding"></ul><p>Ready for review is not authorized execution. Authorized execution is not acceptance after validation. No code or tests ran; Exercise 6 retains its own evidence and approval boundary.</p><div class="actions"><button id="revise" class="primary" type="button">Revise once</button><a href="worked-example.html">Worked alternatives</a></div></section>
<section id="record-panel" class="card" hidden><div class="section-head"><h2>Your review record</h2><button id="copy" class="text-button" type="button">Copy record</button></div><p class="field-note">The initial and revised reviews remain separate in this attempt. Copy before leaving; nothing is saved.</p><pre id="record" tabindex="0"></pre><p id="copy-status" role="status"></p></section><div class="actions end-actions"></div>`,true);
const choiceList=options=>'<ul class="paper-choices">'+options.map(option=>`<li>□ ${esc(option.label)}</li>`).join('')+'</ul>';
function worksheet(card){
  return page('Automation review worksheet · card '+card.id,`${brief}<section class="card"><h2>Assigned authority card ${card.id}</h2><p><strong>Request:</strong> ${esc(card.request)}</p><p><strong>Approval record:</strong> ${esc(card.approval)}</p></section><section class="card print-sources"><h2>Prepared patch and full sources</h2><pre>${esc(M.proposal)}</pre>${sourceDetails.replaceAll('<details class="source">','<details class="source" open>')}</section><section class="card paper-activity"><h2>1 · Review three concerns</h2>${M.groups.map(group=>`<h3>${esc(group.title)}</h3><p class="source-excerpt">${esc(group.excerpt)} [${esc(group.source)}]</p>${choiceList(group.options)}`).join('')}<p class="write-space">One brief source-based explanation:</p><h2>2 · Plan three validation cases</h2><h3>${esc(M.success.title)}</h3><p>${esc(M.success.condition)}</p>${choiceList(M.success.outcomes)}<p>Choose two different faults and one expected outcome/evidence for each:</p>${M.faults.map(fault=>`<h3>□ ${esc(fault.title)}</h3><p>${esc(fault.condition)} [${esc(fault.source)}]</p>${choiceList(fault.outcomes)}`).join('')}<p>Unchosen fault checks, actual results, fixture/session evidence, diagnostics, and policy clarification remain outstanding for later acceptance.</p><h2>3 · Decide authority</h2>${policy}<p><strong>Assigned action:</strong> ${esc(card.request)}</p><p><strong>Assigned approval:</strong> ${esc(card.approval)}</p>${choiceList(M.decisions)}<p class="write-space">Short reason for allow, block, or defer:</p><h2>Commit before feedback</h2><p>Mark this as your initial review. Only then open <a href="feedback.html">prepared feedback</a>. Preserve this sheet and record one revision below or on a copy.</p><p class="write-space">Revision and why it changed:</p><p>No patch or comparison runs. No validation result is available.</p></section>`);
}
const feedback=page('Automation review feedback',`<section class="card"><p>Read after your initial review. <a href="worksheet-A.html">Return to a worksheet</a>. These explanations support discussion; a person must review your written reasons.</p>${M.groups.map(group=>`<h2>${esc(group.title)} · ${esc(group.source)}</h2>${group.options.map(option=>`<h3>${esc(option.label)}</h3><p>${esc(option.explanation)}</p>`).join('')}`).join('')}<h2>Validation outcomes</h2><h3>${esc(M.success.title)}</h3>${M.success.outcomes.map(option=>`<p><strong>${esc(option.label)}</strong> ${esc(option.explanation)}</p>`).join('')}${M.faults.map(fault=>`<h3>${esc(fault.title)}</h3>${fault.outcomes.map(option=>`<p><strong>${esc(option.label)}</strong> ${esc(option.explanation)}</p>`).join('')}`).join('')}<p>Two deliberately faulty cases complete the classroom task. The unchosen faults, actual execution results, fixture/session evidence, diagnostics, and policy clarification stay outstanding for later acceptance.</p><h2>Assigned authority cards</h2><p>Card A has matching scope for a test-branch patch, but unresolved technical concerns can still hold it. Card B's patch approval does not authorize a comparison run; defer for matching approval or block the current request with that reason. Card C requests prohibited production action and must be blocked. A matching record never grants merge or production authority and does not make a patch correct.</p><p>Keep the initial review, then revise once. Ready for review, authorized to execute, and accepted after validation are separate. This activity cannot establish the last state or diagnose run 204.</p><a href="worked-example.html">Worked alternatives</a></section>`);
const examples=[
  {title:'Card A · reviewed proposal, limited authority',s:{wait:'retain',credentials:'fresh',policy:'defer',rationale:'TIM-01 supports the submission deadline; AC-04 and DATA-01 require independent fresh-session checks. No approved source defines a length rule.',successOutcome:'pass',faultIds:['late','oldWorks'],faultOutcomes:{late:'fail',oldWorks:'fail'},cardId:'A',decision:'allow',permissionReason:'The designated reviewer approved this test-branch patch only. Validation, merge, and production remain separate.'}},
  {title:'Card B · request exceeds approval',s:{wait:'retain',credentials:'fresh',policy:'remove',rationale:'TIM-01 supports the wait, AC-04 and DATA-01 require fresh sessions, and the supplied ACs do not approve a length rule.',successOutcome:'pass',faultIds:['error','newFails'],faultOutcomes:{error:'fail',newFails:'fail'},cardId:'B',decision:'defer',permissionReason:'The approval covers patch application, not this isolated comparison; request matching scoped approval.'}},
  {title:'Card C · prohibited production action',s:{wait:'retain',credentials:'fresh',policy:'defer',rationale:'The wait follows TIM-01; credentials need AC-04/DATA-01 checks; length policy needs clarification.',successOutcome:'pass',faultIds:['late','newFails'],faultOutcomes:{late:'fail',newFails:'fail'},cardId:'C',decision:'block',permissionReason:'Production credential actions are prohibited in the workshop, regardless of encouragement.'}}
];
const worked=page('Worked review alternatives',`<section class="card"><p>Read after an initial decision. These are authored examples, not validation results.</p>${examples.map(({title,s})=>`<h2>${esc(title)}</h2><pre>${esc(M.record(s))}</pre><details><summary>Why this is defensible and what remains open</summary><pre>${esc(M.feedbackText(s))}</pre></details>`).join('')}<p>Different pairs of faulty cases and justified blocks or deferrals can be sound. Unchosen checks remain outstanding, and no action actually executes.</p><a href="index.html">Return to Exercise 5</a></section>`);
const template=`# Automation-review record\n\nFictional teaching scenario. No patch or validation executes.\n\n## Review three proposal concerns\n\n| Concern | Retain / revise / defer | Source basis and limit |\n| --- | --- | --- |\n| Synchronization | | |\n| Credential checks | | |\n| Unsupported policy | | |\n\nBrief source-based explanation:\n\n## Three-case validation plan\n\n| Case | Expected test outcome and observable evidence |\n| --- | --- |\n| Delayed valid success | |\n| Deliberate fault 1 | |\n| Deliberate fault 2 | |\n\nUnchosen checks and evidence still needed for acceptance:\n\n## Assigned action and approval\n\nAssigned card / request / approval:\nAllow / block / defer and brief reason:\nTechnical review status and outstanding prerequisite:\n\n## One revision after feedback\n\nPreserve the initial review. Record what changed and why.\nReady for review is not execution authority; authority is not acceptance after validation.\n`;
const files={'index.html':index,'worksheet.html':worksheet(M.cardFor('A')),'worksheet-A.html':worksheet(M.cardFor('A')),'worksheet-B.html':worksheet(M.cardFor('B')),'worksheet-C.html':worksheet(M.cardFor('C')),'feedback.html':feedback,'worked-example.html':worked,'workflow-template.md':template};
for(const [name,content] of Object.entries(files)){
  const file=path.join(__dirname,name);
  if(process.argv.includes('--check')){if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==content)throw Error('Stale generated file: '+name);}
  else fs.writeFileSync(file,content);
}
console.log(process.argv.includes('--check')?'Generated pages are current.':'Generated exercise, three assigned worksheets, feedback, worked examples, and template.');
