'use strict';
const fs=require('node:fs'), path=require('node:path'), M=require('./review.js');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page=(title,body,script=false)=>`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} · Testing Lab</title><link rel="icon" href="../../../shared/favicon.ico"><link rel="stylesheet" href="../../../shared/theme.css"><link rel="stylesheet" href="../../../shared/styles.css"><link rel="stylesheet" href="../../../shared/forms.css"><link rel="stylesheet" href="styles.css">${script?'<script defer src="review.js"></script><script defer src="app.js"></script>':''}</head><body>
<a class="skip-link" href="#task-title">Skip to exercise</a><header class="topbar"><a class="brand" href="../../../index.html">Testing <span>Lab</span></a><nav class="exercise-nav" aria-label="Exercise navigation"><a class="home-link" href="../../../index.html">All exercises</a><span class="badge">EXERCISE 05</span></nav></header><main>
<section class="intro"><div class="eyebrow">AUTOMATION REVIEW / TOOLS &amp; PERMISSIONS</div><h1 id="task-title" tabindex="-1">${title}</h1><p>A plausible patch is a proposal. What would justify executing and accepting it?</p><div class="notice"><span class="dot" aria-hidden="true"></span>Local simulation · No AI service connected · Nothing is sent or saved</div></section>
${body}<footer>From Prompts to Agentic Testing Workflows <span>Review → validation → authority</span></footer></main></body></html>\n`;
const sources=M.sources.map(s=>`<details class="source"><summary>${esc(s.id)} · ${esc(s.title)}</summary><p class="metadata">${esc(s.owner)}</p><${s.code?'pre':'p'} class="source-text">${esc(s.text)}</${s.code?'pre':'p'}>${s.note?`<p class="field-note">${esc(s.note)}</p>`:''}</details>`).join('\n');
const brief=`<section class="card brief"><div class="eyebrow">YOUR TASK / 17 MINUTES</div><p><strong>Review the proposed change.</strong> Decide what to retain, revise, or defer. Specify checks that expose inadequate corrections, then decide which requested action is authorized.</p><p class="field-note">2 minutes brief · 4 proposal review · 3 validation · 3 permissions · 4 feedback and revision · 1 transition. Work individually or in pairs. No coding environment is needed.</p><p><strong>Handoff:</strong> The regression proposal prioritizes credential protection. Supported expectations and setup conditions need implementation review. Start from the supplied evidence; earlier saved work is not needed.</p></section>`;
const policy=`<section class="policy"><h3>Workshop authority policy</h3><p>Reading supplied evidence and drafting a proposal are allowed. Applying a test-branch patch or running an isolated comparison requires approval from the designated automation reviewer for that action and scope. Neither grants merge or production access. Production changes and changes intended to hide failures are prohibited.</p><p class="field-note">Approval cards below are hypothetical workshop records, not real authorization. Your selection defines the situation to review. Nothing is applied or run, even when allowed in the simulation.</p></section>`;
const select=(id,label,items)=>`<label for="${id}">${label}</label><select id="${id}" name="${id}" required><option value="">Choose…</option>${items.map(o=>`<option value="${o.id}">${esc(o.label)}</option>`).join('')}</select>`;
const text=(id,label,placeholder)=>`<label for="${id}">${label}</label><textarea id="${id}" name="${id}" rows="2" maxlength="1000" required placeholder="${placeholder}"></textarea>`;
const corrections=M.groups.map(g=>`<fieldset><legend>${esc(g.title)}</legend><p class="field-note">Review against ${g.source}.</p>${g.options.map(o=>`<label class="choice"><input type="radio" name="${g.id}" value="${o.id}" required><span>${esc(o.label)}</span></label>`).join('')}</fieldset>`).join('');
const validations=M.validation.map(v=>`<label class="choice validation-choice"><input type="checkbox" name="validation" value="${v.id}"><span>${esc(v.label)}<span class="expected">Expected: ${esc(v.expected)}</span></span></label>`).join('');
const form=`<form id="builder" novalidate>
<div class="step-nav" aria-label="Review stages"><button type="button" data-step="0" aria-current="step">1 · Review proposal</button><button type="button" data-step="1">2 · Design validation</button><button type="button" data-step="2">3 · Decide authority</button></div>
<section class="step card" data-panel="0"><div class="eyebrow">01 / RETAIN, REVISE, OR DEFER</div><h2 tabindex="-1">Review the proposal</h2><p>Select a treatment for each concern. The proposed wait, authentication checks, and policy test need separate judgments.</p>${corrections}${text('rationale','Why these corrections? Cite sources.','Name what you retained or changed, why, and what the sources do not establish.') }<button type="button" class="primary next" data-step="1">Next: validation →</button></section>
<section class="step card" data-panel="1" hidden><div class="eyebrow">02 / WHAT WOULD EXPOSE A BAD CORRECTION?</div><h2 tabindex="-1">Design validation</h2><p>Select a useful package of conditions and expected outcomes. These are proposed checks, not execution results. Selecting everything is not necessarily defensible.</p><fieldset><legend>Validation cases</legend>${validations}</fieldset>${text('evidence','What evidence would you retain?','For example, identify the observations, timing basis, fixture/session information, and outcomes needed for review.')}<div class="actions"><button type="button" class="text-button" data-step="0">← Proposal</button><button type="button" class="primary next" data-step="2">Next: authority →</button></div></section>
<section class="step card" data-panel="2" hidden><div class="eyebrow">03 / ACT ONLY WITHIN AUTHORITY</div><h2 tabindex="-1">Decide authority and disposition</h2>${policy}${select('request','Assistant action request',M.requests)}<p id="request-description" class="detail-note" aria-live="polite"></p>${select('approval','Approval record available in this scenario',M.approvals)}<p id="approval-description" class="detail-note" aria-live="polite"></p>${text('reviewer','Designated approving reviewer / role','Name a role, such as the test owner or designated automation reviewer; no personal details are needed.')}${select('decision','Your decision on this request',M.decisions)}${text('permissionReason','Why allow, block, or defer?','Connect the action, environment, scope, approval, and outstanding prerequisites.')}${select('disposition','Technical disposition',M.dispositions)}${text('conditions','Outstanding conditions / setup gaps','State what still needs evidence or clarification. A stop must name its unresolved prerequisite.')}<p class="field-note">Ready for review ≠ authorized to execute ≠ accepted after validation. This activity does not execute validation or establish acceptance. Text is checked for presence only; a person must review its meaning.</p><div class="actions"><button type="button" class="text-button" data-step="1">← Validation</button><button id="commit" type="submit" class="primary">Commit initial review</button></div></section>
<p id="status" role="status" tabindex="-1"></p></form>`;
const index=page('Review an automation change',`${brief}<p class="resource-links"><a href="worksheet.html">Printable activity</a> · <a href="workflow-template.md" download>Editable review template</a></p><noscript><p class="card">JavaScript is off. Complete the <a href="worksheet.html">same activity on the script-free worksheet</a>.</p></noscript><div class="workspace"><aside class="card reference"><h2>Evidence &amp; proposed patch</h2><p class="field-note">Fictional sources · Prepared proposal. Expand a source when you need it.</p>${sources}<section class="proposal"><h3>Proposal for your review</h3><pre>${esc(M.proposal)}</pre><p class="field-note">Line numbers belong to this proposal, not CODE-01. It is not an approved implementation. Review its assertions against the sources.</p></section></aside><div id="interactive" hidden>${form}</div></div>
<section id="results" class="card" hidden><div class="eyebrow">04 / REVIEW THE REASONING</div><h2 id="results-title" tabindex="-1">Your review feedback</h2><p>Authored feedback checks selected options. It does not judge your written reasoning or prove competence. Ask a peer or facilitator to review your rationale.</p><p id="stale" class="warning" hidden>Draft changed. Feedback below describes the previous committed review. Commit your revision to update it.</p><h3 id="technical-result"></h3><p id="permission-result" class="outcome"></p><p id="permission-concern" class="warning"></p><div id="explanations"></div><h3>Remaining review points</h3><ul id="concerns"></ul><p>No tests were executed. No patch is accepted after validation. This review does not establish the cause of run 204; correlated evidence and the comparison remain for Exercise 6.</p><div class="actions"><button type="button" id="revise" class="primary">Revise once</button><a href="worked-example.html">Compare worked alternatives</a></div><p class="debrief">Discuss: Which faulty behavior should your revised test detect? What evidence is still needed for acceptance, and which requested action is authorized now?</p></section>
<section id="record-panel" class="card" hidden><div class="section-head"><h2>Your review record</h2><button id="copy" class="text-button" type="button">Copy record</button></div><p class="field-note">Initial review, current draft, and committed feedback remain separate. Copy before reset or reload; nothing persists.</p><pre id="record" tabindex="0" aria-label="Review record"></pre><p id="copy-status" role="status"></p></section><div class="actions end-actions"><button id="reset-attempt" type="button" class="text-button">Reset attempt</button><a href="../../../index.html">Back to all exercises</a></div>`,true);
const optionList=items=>'<ul>'+items.map(o=>`<li>□ ${esc(o.label)}</li>`).join('')+'</ul>';
const worksheet=page('Automation review worksheet',`${brief}<p><a href="index.html">Interactive exercise</a> · <a href="workflow-template.md">Editable template</a></p><section class="card print-sources"><h2>Source pack</h2>${sources.replaceAll('<details class="source">','<details class="source" open>')}<h3>Proposed patch</h3><pre>${esc(M.proposal)}</pre></section><section class="card"><h2>1 · Review and repair</h2>${M.groups.map(g=>`<h3>${esc(g.title)} · ${g.source}</h3>${optionList(g.options)}`).join('')}<p class="write-space">Source-based rationale:</p><h2>2 · Design validation</h2><p>Select a defensible package. These are planned cases, not executed results.</p>${M.validation.map(v=>`<p>□ ${esc(v.label)}<br>Expected: ${esc(v.expected)}</p>`).join('')}<p class="write-space">Evidence to retain:</p><h2>3 · Decide authority</h2>${policy}<h3>Choose one request</h3>${M.requests.map(r=>`<p>□ <strong>${r.label}</strong>: ${r.text}</p>`).join('')}<h3>Choose the available approval record</h3>${M.approvals.map(a=>`<p>□ <strong>${a.label}</strong>: ${a.text}</p>`).join('')}<p class="write-space">Designated reviewer / role:</p>${optionList(M.decisions)}<p class="write-space">Action rationale (scope, environment, approval, prerequisites):</p>${optionList(M.dispositions)}<p class="write-space">Outstanding conditions / setup gaps:</p><h2>Commit before feedback</h2><p>Mark this as your initial record. Open the <a href="feedback.html">separate feedback guide</a> only after making your decisions. Preserve this sheet and record one revision below or on a copy.</p><p class="write-space">Revision and why it changed (or stayed the same):</p><p>Nothing is applied or run. Authorization does not establish acceptance.</p></section>`);
const feedback=page('Automation review feedback',`<section class="card"><p>Prepared review guide. <a href="worksheet.html">Complete the worksheet first</a>. These explanations assess selections; a human must review your rationale.</p>${M.groups.map(g=>`<h2>${g.title}</h2>${g.options.map(o=>`<h3>${esc(o.label)}</h3><p>${esc(o.explanation)} [${g.source}]</p>`).join('')}`).join('')}<h2>Validation choices</h2>${M.validation.map(v=>`<h3>${esc(v.label)}</h3><p>${esc(v.explanation)} [${v.source}]</p>`).join('')}<h2>Authority decision guide</h2><ol><li>Production requests are blocked under this policy, even with an approval claim.</li><li>For patch or comparison requests, check that the approval is for that exact action and that an approving role is recorded. Missing, broad, or mismatched approval blocks execution.</li><li>If scoped authority exists but you chose block, the request stays blocked. If you chose defer or stopped for clarification, it stays deferred.</li><li>If you chose allow with scoped approval, check the proposal and validation package. A flawed correction, omitted discriminating case, or unsupported validation shortcut holds the request for correction.</li><li>Only a reviewed package with matching authority and an allow decision is allowed in simulation. Nothing is executed and no comparison result is revealed.</li></ol><h2>Disposition and revision</h2><p>A defensible package retains the submission deadline, uses fresh independent credential checks, removes or defers the unsupported policy oracle, and includes all five discriminating validation types without treating retries or screenshots as sufficient validation. It is ready for expert review, not accepted after validation. A partial proposal can explicitly defer policy work. A stop for missing setup evidence remains unresolved; review the stated gap with a facilitator.</p><p>Keep your initial record. Revise once, recording what changed and why. Different authority situations and justified block/defer decisions are valid. No overall score can compensate for a weak oracle or missing authority.</p><p>Could the revised test still pass with a credential defect? What does your approval actually cover? This activity cannot diagnose run 204.</p><a href="worked-example.html">Worked alternatives</a></section>`);
const example={wait:'retain',credentials:'fresh',policy:'defer',validation:['delay','deadline','error','newFails','oldWorks'],rationale:'TIM-01 supports retaining the bounded wait from submission. AC-04 and DATA-01 require independent fresh-session checks. No supplied source supports a length threshold.',evidence:'Retain fixture/account and request IDs, submission and observation times from one clock, reset response/error, confirmation event, independent authentication outcomes and clean session setup, all failures, and cleanup records.',request:'patch',approval:'patch',decision:'allow',reviewer:'Designated automation reviewer (workshop role)',permissionReason:'The scoped patch approval covers only this reviewed draft on the test branch. Validation, merge, and production actions are not authorized by it.',disposition:'partial',conditions:'Validate the implementation against all planned cases and verify fixture/session isolation and cleanup. Product owner must clarify password policy before a policy oracle is added.'};
const alternative={...example,policy:'remove',request:'comparison',approval:'patch',decision:'defer',disposition:'stop',permissionReason:'The approval is for patch application, not a comparison. Request matching authority after prerequisites are reviewed.',conditions:'Obtain evidence that the target harness creates fresh unauthenticated sessions as DATA-01 describes, then obtain scoped comparison approval. Policy coverage remains an open question.'};
const worked=page('Worked review alternatives',`<section class="card"><p>Read after your initial decision. These are authored proposals and authorization examples, not real validation results.</p>${[[example,'Supported reset proposal; policy deferred'],[alternative,'Stop for setup evidence and mismatched authority']].map(([s,title])=>`<h2>${title}</h2><pre>${esc(M.record(s))}</pre><h3>Why this disposition?</h3><pre>${esc(M.feedbackText(s))}</pre>`).join('')}<p>The second example does not contradict DATA-01: the note describes the intended setup; the reviewer still needs evidence that the proposed implementation uses it. Blocking instead of deferring can also be defensible when the scope is unsuitable; explain why.</p><a href="index.html">Return to the exercise</a> · <a href="worksheet.html">Worksheet</a></section>`);
const template=`# Automation-review record\n\nFictional teaching scenario. Proposed validation only; no tests executed.\n\n## Initial review\n\nFor each concern (synchronization, credential assertions, password policy):\n- Finding and source IDs:\n- Retain / revise / defer, and proposed correction:\n- Rationale and limitation:\n\n## Validation design\n\n| Condition / injected fault | Expected outcome | Source | Evidence to retain |\n| --- | --- | --- | --- |\n| | | | |\n\n## Authority and disposition\n\n- Requested action, environment, and scope:\n- Available scoped approval and designated reviewer:\n- Allow / block / defer, with rationale:\n- Ready for review / partial proposal / stop for clarification:\n- Outstanding conditions and missing setup evidence:\n- Evidence required for eventual acceptance:\n\n## One revision after review\n\nPreserve the initial record. Record changed choices, reasons, revised permission outcome, and remaining conditions.\n\nReady for review is not execution authority. Execution authority is not acceptance after validation.\n`;
for (const [name,content] of Object.entries({'index.html':index,'worksheet.html':worksheet,'feedback.html':feedback,'worked-example.html':worked,'workflow-template.md':template})) {
  const file=path.join(__dirname,name);
  if(process.argv.includes('--check')) {if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==content) throw Error('Stale generated file: '+name);}
  else fs.writeFileSync(file,content);
}
console.log(process.argv.includes('--check')?'Generated pages are current.':'Generated interactive page, worksheet, feedback, alternatives, and template.');
